### ISSUE TITLE
安装tvbox一直报错

### ISSUE THREAD

**Issue by clippers0318** [DDS-Derek/xiaoya-alist#104]
如题

执行bash -c "$(curl --insecure -fsSL https://ddsrem.com/xiaoya_install.sh)"

选择安装tvbox时最后报错
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 127.0.0.53:53: no such host
[ERROR] 镜像拉取失败！

系统是ubuntu 2204

不知道如何处理

**Comment by DDSDerek** [comment]
网络问题
