### ISSUE TITLE
添加额外参数有具体格式么？

### ISSUE THREAD

**Issue by geryson911** [DDS-Derek/xiaoya-alist#11]
添加额外参数有具体格式么？例如说添加显卡硬解 --device=/dev/dri是这样配置么

**Comment by DDSDerek** [comment]
先执行脚本选择`7`，然后`2`
![image](https://github.com/DDS-Derek/xiaoya-alist/assets/108336573/1a2decc3-fa2a-4eb2-90c1-5584d2154f23)
开启后返回主菜单运行安装emby的过程就会提示是否要设置额外参数，把` --device=/dev/dri`输入就行
