### ISSUE TITLE
最近docker 无法访问，曲线救国安装的xiaoya无法清除，安装的时候提示请先安装docker，感觉是匹配docker的时候没有校验出来

### ISSUE THREAD

**Issue by lifeifeng2024** [DDS-Derek/xiaoya-alist#113]
[**xxxxxxxxxx** ~]$ bash -c "$(curl -sLk https://xiaoyahelper.ddsrem.com/aliyun_clear.sh | tail -n +2)" -s 3 -tg
你还没有安装小雅docker，请先安装！

实际安装有
[**xxxxxxxxxx**~]$ docker images -a
REPOSITORY                                                 TAG       IMAGE ID       CREATED         SIZE
registry.cn-hangzhou.aliyuncs.com/**xxxxxxxx**/alist   latest    1e9bc90067d7   8 days ago      54MB

PS (xxxxx做了隐藏处理)

**Comment by DDSDerek** [comment]
这种问题脚本不做适配，请自行在创建容器前用docker tag命令把镜像名称改成官方名称的样式再创建容器
