### ISSUE TITLE
tvbox 反代后接口地址不正确

### ISSUE THREAD

**Issue by iGwkang** [DDS-Derek/xiaoya-alist#117]
1. tvbox接口 `http://10.0.0.4:5678/tvbox/my_ext.json`
2. nginx通过https协议，端口8443反代 `http://10.0.0.4:5678`
3. 使用浏览器访问 `https://alist.mydomain.com:8443/tvbox/my_ext.json`
4. json中的api接口以及server地址 变成了 `http://alist.mydomain.com`  https协议变成了http，并且端口也没了
5. nginx反代配置
```
  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_set_header X-Real-IP          $remote_addr;
    proxy_pass       http://10.0.0.4:5678;
  }
```

**Comment by iGwkang** [comment]
解决方法
1. 修改nginx反代配置
`proxy_set_header Host $host;` 加上端口 `proxy_set_header Host $host:8443;`

2. 修改xiaoya-alist容器中 nginx的配置
`vi /etc/nginx/http.d/default.conf`

在server外面插入
```
map $http_x_forwarded_proto $client_scheme {    
    default $http_x_forwarded_proto;    
    '' $scheme;    
}
```
将`
sub_filter "DOCKER_ADDRESS" $scheme://$http_host;`  中的`$scheme`改为`$client_scheme`

![image](https://github.com/DDS-Derek/xiaoya-alist/assets/35400668/15c9ac2a-f974-428f-8ea1-fd22deadf95f)

`nginx -s reload`

这样虽然能够解决，但是还是希望能够适配一下

**Comment by DDSDerek** [comment]
小雅镜像已修改
