### ISSUE TITLE
 希望安装命令能有个快捷命令  安装后 直接“xy”就可以不用再去复制粘贴全部命令

### ISSUE THREAD

**Issue by Haiqinggit** [DDS-Derek/xiaoya-alist#118]

**Comment by DDSDerek** [comment]
一直都有，命令行输入xiaoya就可以直接调用脚本

**Comment by Yaonie-Jie** [comment]
![image](https://github.com/DDS-Derek/xiaoya-alist/assets/24479437/816e22d8-0cd4-42c7-a442-b9ca9bcfe11a)
我这个不行，重连服务器也不行 是不是没有添加到环境变量，我应该如何手动添加一下？

**Comment by Haiqinggit** [comment]
> 一直都有，命令行输入xiaoya就可以直接调用脚本

感谢 试了可以的
