### ISSUE TITLE
jellyfin全家桶 3-1 安装一直错误提示 求情帮助

### ISSUE THREAD

**Issue by tian4546** [DDS-Derek/xiaoya-alist#122]
![xiaoya](https://github.com/DDS-Derek/xiaoya-alist/assets/14542275/41a24840-1bac-452d-9c7d-45b403bd4d8e)
而且每次这一步是吧了又的重新解压 100+G的文件，感觉要优化一下，这个地方已经解压完成，重新安装直接跳过解压

然后这一步失败 ，我手动绑定host 也不行，安装了5 6边 全到这一步失败

**Comment by tian4546** [comment]
不管是自动获取 10.0.5.1 还是我手动 指定 容器的具体ip 都是不行，还是需要 用NAS的ip 加端口了， 用的是威联通 5.2QTS 系统，然后用的是2个网口都插了

**Comment by tian4546** [comment]
刚才用家里的 群晖也试了一下 也是报这个错误 ，不兼容呀，群晖只有1个网口

**Comment by ruben6066** [comment]
你好，请问解决了么？我也遇到相同的问题了。
