### ISSUE TITLE
夸克

### ISSUE THREAD

**Issue by cstybbt** [DDS-Derek/xiaoya-alist#123]
每日更新/电视剧/国产剧（夸克）都不能播放
log显示获取目录失败，安装就填了阿里云的三个参数。是哪里要设置夸克的参数吗？
2024/06/18 12:14:18.779170 ERROR RESTY Get "https://drive-pc.quark.cn/1/clouddrive/config?fr=pc&pr=ucpro": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 1
2024/06/18 12:14:28.883846 ERROR RESTY Get "https://drive-pc.quark.cn/1/clouddrive/config?fr=pc&pr=ucpro": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 2
2024/06/18 12:14:39.071743 ERROR RESTY Get "https://drive-pc.quark.cn/1/clouddrive/config?fr=pc&pr=ucpro": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 3
2024/06/18 12:14:49.073246 ERROR RESTY Post "https://drive-pc.quark.cn/1/clouddrive/share/sharepage/token?__dt=&__t=&fr=pc&pr=ucpro&uc_param_str=": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 1
2024/06/18 12:14:59.178684 ERROR RESTY Post "https://drive-pc.quark.cn/1/clouddrive/share/sharepage/token?__dt=&__t=&fr=pc&pr=ucpro&uc_param_str=": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 2
2024/06/18 12:15:09.347456 ERROR RESTY Post "https://drive-pc.quark.cn/1/clouddrive/share/sharepage/token?__dt=&__t=&fr=pc&pr=ucpro&uc_param_str=": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 3
ERRO[2024-06-18 12:15:09] failed get enabled storages: Get "https://drive-pc.quark.cn/1/clouddrive/config?fr=pc&pr=ucpro": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
failed init storage
github.com/alist-org/alist/v3/internal/op.initStorage
        /app/internal/op/storage.go:99
github.com/alist-org/alist/v3/internal/op.LoadStorage
        /app/internal/op/storage.go:80
github.com/alist-org/alist/v3/internal/bootstrap.LoadStorages.func1
        /app/internal/bootstrap/storage.go:26
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1594
INFO[2024-06-18 12:15:09] success load storage: [/©️ v.0618.0429(B)], driver: [UrlTree]
获取目录失败： object not found
文件: /夸克公益/墨雨云间/S01E28.mp4 新增下载直链: https://quark.xiaoya.pro/p/%E5%A4%B8%E5%85%8B%E5%85%AC%E7%9B%8A/%E5%A2%A8%E9%9B%A8%E4%BA%91%E9%97%B4/S01E28.mp4
06-18-2024 12:21:35 Alist_V3 已成功缓存了 1 个文件
获取目录失败： object not found
文件: /夸克公益/城中之城/S01E01.mkv 新增下载直链: https://quark.xiaoya.pro/p/%E5%A4%B8%E5%85%8B%E5%85%AC%E7%9B%8A/%E5%9F%8E%E4%B8%AD%E4%B9%8B%E5%9F%8E/S01E01.mkv
06-18-2024 12:24:45 Alist_V3 已成功缓存了 2 个文件

**Comment by tian4546** [comment]
没看到夸克的 功能呀，你用的不是这个脚本安装的吧

**Comment by stiffme** [comment]
我这里似乎也有同样的问题
`INFO[2024-06-18 18:35:34] success load storage: [/每日更新/电视剧/日剧/【已完结】], driver: [Alias] 
INFO[2024-06-18 18:35:35] success load storage: [/每日更新/电视剧/韩剧/【已完结】], driver: [Alias] 
刷新夸克分享令牌成功： kRg3xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
ERRO[2024-06-18 18:35:35] failed get enabled storages: require login [guest]
failed init storage
github.com/alist-org/alist/v3/internal/op.initStorage
        /app/internal/op/storage.go:99
github.com/alist-org/alist/v3/internal/op.LoadStorage
        /app/internal/op/storage.go:80
github.com/alist-org/alist/v3/internal/bootstrap.LoadStorages.func1
        /app/internal/bootstrap/storage.go:26
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1594 
INFO[2024-06-18 18:35:36] success load storage: [/每日更新/电视剧/日剧（夸克）], driver: [AList V3] 
INFO[2024-06-18 18:35:36] success load storage: [/每日更新/电影/（夸克）], driver: [AList V3] 
INFO[2024-06-18 18:35:37] success load storage: [/©️ v.0618.1827(B)], driver: [UrlTree] 
转存文件失败： S01E01.mkv
获取夸克直链失败 S01E01.mkv require login [guest]
转存文件失败： S01E01.mkv
获取夸克直链失败 S01E01.mkv require login [guest]
转存文件失败： S01E01.mkv
获取夸克直链失败 S01E01.mkv require login [guest]
`

**Comment by cstybbt** [comment]
进了tg群，夸克官方还在完善中

**Comment by stiffme** [comment]
这是不是要配置夸克的token才能使用了？
