### ISSUE TITLE
脚本运行第一步出错

### ISSUE THREAD

**Issue by cchen998** [DDS-Derek/xiaoya-alist#124]
[INFO] docker0 的 IP 地址是：172.17.0.1
[INFO] 测试xiaoya的联通性...
[ERROR] 请先配置 /opt/xiaoya//docker_address.txt 后重试
我在运行其它容器是没有这个错误，请问该如何解决，这个文件需要如何配置？

**Comment by wujun4code** [comment]
我也遇到了这个错误，怎么修复的？ @cchen998

**Comment by KeenM6** [comment]
同问，怎么办呢

**Comment by Guanchishan** [comment]
在网上搜到，按[这个方法](https://www.vumstar.com/forum-post/4624.html/)做应该就行了
