### ISSUE TITLE
安装emby出错，大佬帮忙看看怎么回事

### ISSUE THREAD

**Issue by cchen998** [DDS-Derek/xiaoya-alist#125]
[INFO] 已读取小雅Alist配置文件路径：/opt/xiaoya/ (默认不更改回车继续，如果需要更改请输入新路径)
CONFIG_DIR:
[INFO] 已读取媒体库目录：/opt/media (默认不更改回车继续，如果需要更改请输入新路径)
MEDIA_DIR:
[INFO] docker0 的 IP 地址是：172.17.0.1
[INFO] 测试xiaoya的联通性...
[ERROR] 请检查xiaoya是否正常运行后再试
[ERROR] 小雅日志如下：
06-18-2024 20:44:27 获取新file id失败:  <nil>
06-18-2024 20:44:28 获取新file id失败:  <nil>
06-18-2024 20:44:55 获取新file id失败:  <nil>
06-18-2024 20:44:56 获取新file id失败:  <nil>
06-18-2024 20:44:57 获取新file id失败:  <nil>
06-18-2024 20:45:30 获取新file id失败:  <nil>
06-18-2024 20:45:31 获取新file id失败:  <nil>
06-18-2024 20:45:32 获取新file id失败:  <nil>

Alist打开是正常的。

**Comment by cchen998** [comment]
INFO[2024-06-18 20:43:06] success load storage: [/每日更新/动漫/日本/所有], driver: [Alias] 
INFO[2024-06-18 20:43:06] success load storage: [/电影/杜比视界], driver: [Alias] 
INFO[2024-06-18 20:43:06] success load storage: [/电影/豆瓣 top 1000部], driver: [Alias] 
INFO[2024-06-18 20:43:06] success load storage: [/电影/人人影视电影合集], driver: [Alias] 
INFO[2024-06-18 20:43:06] success load storage: [/电子书/epub合集], driver: [Alias] 
INFO[2024-06-18 20:43:06] success load storage: [/电子书/azw3合集], driver: [Alias] 
INFO[2024-06-18 20:43:06] success load storage: [/动漫/儿童], driver: [Alias] 
INFO[2024-06-18 20:43:06] success load storage: [/动漫/儿童/宫崎骏-合集], driver: [Alias] 
INFO[2024-06-18 20:43:06] success load storage: [/动漫/儿童/新海诚-系列], driver: [Alias] 
INFO[2024-06-18 20:43:07] success load storage: [/纪录片/4K REMUX], driver: [Alias] 
INFO[2024-06-18 20:43:07] success load storage: [/每日更新/电视剧/日剧/【已完结】], driver: [Alias] 
INFO[2024-06-18 20:43:07] success load storage: [/每日更新/电视剧/韩剧/【已完结】], driver: [Alias] 
INFO[2024-06-18 20:43:07] success load storage: [/每日更新/电视剧/国产剧（夸克）], driver: [AList V3] 
INFO[2024-06-18 20:43:07] success load storage: [/每日更新/电视剧/日剧（夸克）], driver: [AList V3] 
INFO[2024-06-18 20:43:07] success load storage: [/每日更新/电影/（夸克）], driver: [AList V3] 
INFO[2024-06-18 20:43:07] success load storage: [/©️ v.0618.1827(B)], driver: [UrlTree] 
06-18-2024 20:43:24 获取新file id失败:  <nil>
06-18-2024 20:43:25 获取新file id失败:  <nil>
06-18-2024 20:43:25 获取新file id失败:  <nil>
获取目录失败： object not found
06-18-2024 20:44:13 获取新file id失败:  <nil>
06-18-2024 20:44:14 获取新file id失败:  <nil>
06-18-2024 20:44:27 获取新file id失败:  <nil>
06-18-2024 20:44:28 获取新file id失败:  <nil>
06-18-2024 20:44:55 获取新file id失败:  <nil>
06-18-2024 20:44:56 获取新file id失败:  <nil>
06-18-2024 20:44:57 获取新file id失败:  <nil>
06-18-2024 20:45:30 获取新file id失败:  <nil>
06-18-2024 20:45:31 获取新file id失败:  <nil>
06-18-2024 20:45:32 获取新file id失败:  <nil>

**Comment by swibignw** [comment]
token 换一个就好了

**Comment by swibignw** [comment]
5

**Comment by shooray** [comment]
> token 换一个就好了

用的是[xiaoyaliu](https://gitlab.com/xiaoyaliu/data)最新8月30日的
![image](https://github.com/user-attachments/assets/e29f9555-3ce0-4754-98f9-ba8130c9b65b)
分享token和open token都换了，xiaoya docker删了重装好多遍，统统不行。
![image](https://github.com/user-attachments/assets/36517653-08fa-4b3c-8eaa-ae8a99c3a392)

全部文件都打不开，怎么办？
![image](https://github.com/user-attachments/assets/6e2f7786-023f-41a4-8af3-8cee530b2c55)
![image](https://github.com/user-attachments/assets/64b2b5f1-9801-43e2-ad11-030990d41a5d)

感觉小雅alist废了-_-

**Comment by Ersticke** [comment]
解决了吗
