### ISSUE TITLE
要重复安装xiaoya吗？

### ISSUE THREAD

**Issue by guugg** [DDS-Derek/xiaoya-alist#128]
比如我想就安装小雅Alist-TVBox。 如果我想要Emby，按照脚本是需要安装xiaoya docker版本的

**Comment by a5412398** [comment]
有教程：https://www.bilibili.com/video/BV1Zf421R7zW/?spm_id_from=333.999.0.0&vd_source=6f3673757daea2599a5831cbd0e6a502
