### ISSUE TITLE
关于resilio与小雅数据不一样的问题，emby搜不到但是小雅界面可以看到

### ISSUE THREAD

**Issue by adaonline** [DDS-Derek/xiaoya-alist#132]
例如现在在resilio设置的
“/volume1/docker/xiaoya/media/xiaoya/每日更新/电影“同步
这个文件夹里香港是没有九龙城寨的，
但是打开小雅界面是有的
![image](https://github.com/DDS-Derek/xiaoya-alist/assets/6014822/9ce5ed6d-02e6-4aa8-bd61-2ec0eb237ea7)
docker文件里查看是没有的
![image](https://github.com/DDS-Derek/xiaoya-alist/assets/6014822/1ec2f5eb-aa7b-4062-9a02-694aec1adf76)
导致emby其实是搜不到的
![image](https://github.com/DDS-Derek/xiaoya-alist/assets/6014822/49a4d529-0943-46c9-87b6-184f19913faf)

所以原因是resilio同步太慢了吗，我设置的resilio 同步是在一键脚本里安装resilio的两天一次，每天6点默认
小雅是每天docker restart
原因是小雅元数据比较快更新还是什么呢？？

如果是这样的话，如何再次设置resilio？我想保持 emby跟小雅数据尽量一致。
亦或者有别的原因，希望告知，感谢啦！

**Comment by 1018987534** [comment]
一样的问题，没法解决，现在都11月了，同步的数据还是8月的
