### ISSUE TITLE
emby  Premiere 注册问题

### ISSUE THREAD

**Issue by datianshi0605** [DDS-Derek/xiaoya-alist#134]
进行了多次，安装了小雅全家桶和emby 非快乐版 ，安装完成后，我用已有的  Premiere的key 进行注册 第一次是可以的，但是只要是稍等一些时间，在切换到的 Premiere 的注册页面，该页面就一直处于加载状态，无法显示结果，想了解这个是个什么问题，可以怎么解决呢 ？

**Comment by sfzx584** [comment]
我也是 啥情况 正版验证401了

**Comment by sfzx584** [comment]
找到方法了 删除docker/xiaoya/media/config/data/device.txt 文件

**Comment by datianshi0605** [comment]
哈哈，看来我们遇到的问题不是同一个，我根据的我遇到的问题是，我做了clashmeta ，其认证服务器的执行走了代理，服务器回馈的时候，找不到来源了，被代理服务器关掉就好了，或者做一个策略，对于指定的域名直链就好
