### ISSUE TITLE
Error response from daemon: No such container: emby

### ISSUE THREAD

**Issue by uiiang** [DDS-Derek/xiaoya-alist#15]
安装emby时报错
Error response from daemon: No such container: emby
不论是一键安装全部，还是选择emby任何版本，都报这个错

**Comment by DDSDerek** [comment]
无法判断问题，请提供更多日志，把完整的过程截图或者复制下来

**Comment by uiiang** [comment]
> 无法判断问题，请提供更多日志，把完整的过程截图或者复制下来
![微信截图_20240221125446](https://github.com/DDS-Derek/xiaoya-alist/assets/346628/2a6caf2d-d8e2-43e5-9e1b-6c33a365e1be)
win11+wsl+ubuntu amd的cpu

**Comment by DDSDerek** [comment]
好的，感谢反馈，目前脚本还没有支持wsl＋Ubuntu类似的这种的环境，大概率以后也不会支持，只能辛苦手动安装了！

或者可以参考官方的脚本尝试安装
