### ISSUE TITLE
p7zip解压速度极慢，是否可以优化？

### ISSUE THREAD

**Issue by dsf1995cn** [DDS-Derek/xiaoya-alist#150]
p7zip是使用单线程解压，config.mp4下载很快，但是解压超过9小时还在跑着，未完成。我这个是个例，还是其他朋友也是这么慢吗？
是否可以使用别的（支持多线程）解压的命令行工具代替？

开始时间：
<img width="1670" alt="Snipaste_2024-07-17_13-20-52" src="https://github.com/user-attachments/assets/b16b5563-7ac5-4760-831a-2e9605fb6f3d">

当前时间：
<img width="1726" alt="Snipaste_2024-07-17_13-21-24" src="https://github.com/user-attachments/assets/115e5075-eb09-425f-a2e0-e776c3bd82e7">

机器配置12100+8G ram。

**Comment by DDSDerek** [comment]
7z已经开启多线程解压了，有可能是你的进程卡死了

**Comment by DDSDerek** [comment]
有可能是进程卡死了，建议自己检查一下进程状态

**Comment by dsf1995cn** [comment]
我当前反馈的这个7z进程状态是S+。
<img width="1864" alt="Snipaste_2024-07-17_14-30-23" src="https://github.com/user-attachments/assets/3e7f9e4a-9781-4e43-a4bd-3883448c4b34">

CTRL+C停止脚本，重新运行，看到新的7z进程状态也是S+。
<img width="1666" alt="Snipaste_2024-07-17_14-35-16" src="https://github.com/user-attachments/assets/a33ca3c5-0b2c-4c65-b368-674a8b7b46d9">
