### ISSUE TITLE
template parsing error: template: :1:2: executing "" at <index .RepoDigests 0>: error calling index: reflect: slice index out of range

### ISSUE THREAD

**Issue by cyclestudy** [DDS-Derek/xiaoya-alist#154]
template parsing error: template: :1:2: executing "" at <index .RepoDigests 0>: error calling index: reflect: slice index out of range

**Comment by 3543776055** [comment]
我也是

**Comment by DDSDerek** [comment]
无需在意，不会影响正常的流程

**Comment by 3543776055** [comment]
> 无需在意，不会影响正常的流程

但是我这里出现这条之后就一直卡在这里
