### ISSUE TITLE
j1900黑群晖跑着脚本搭建emby全家桶提示xiaoya连接不上解决方式~

### ISSUE THREAD

**Issue by alexallen1** [DDS-Derek/xiaoya-alist#16]
进ssh获得sudo -i root后
运行
bash -c "$(curl -sL https://ddsrem.com/xiaoya_install.sh)"

就是趁着刚搭建好xiaoya alist 5分钟之前5678有画面，但刷不出列表有个月亮的'载入中'状态，
立马搭建emby全家桶才行。晚了的话，5678完全载入成功，出列表了，emby就搭不起来（提示找不到xiaoya连接不上）

重现了好几次这样。不知道是不是只是我的问题…………

**Comment by DDSDerek** [comment]
这边修复了，有问题再反馈
