### ISSUE TITLE
转存只能用阿里网盘吗？

### ISSUE THREAD

**Issue by shaynez** [DDS-Derek/xiaoya-alist#167]
阿里限速了，绑了夸克网盘，但是每次看电影转存的时候还是用的阿里网盘，小白用户想问一下，需要把绑定的阿里网盘删了才会用夸克网盘吗？ 还是转存只能用阿里网盘？谢谢

**Comment by a5412398** [comment]
小雅只能阿里，可以通过alist-tvbox里面的添加115cookie，开启115转存，改为转存到115网盘，不限速。不过115也有限制，5G以上的文件就转存不进去。
