### ISSUE TITLE
115清理助手怎样才能清理根目录下的缓存文件

### ISSUE THREAD

**Issue by langoyb** [DDS-Derek/xiaoya-alist#188]
按照小雅官方文档设置ali2115.txt，发现阿里云盘文件是缓存到115根目录下的，并没有到我的接收文件夹内，是我的操作姿势不对吗？大佬的115清理助手指定清理/我的接收和回收站里面的文件，并不能清理根目录下的转存文件，这样就不能达到自动清理转存的目的。不知大家有没有遇到这个问题，应该怎样解决？谢谢！

**Comment by langoyb** [comment]
五分钟之后灵光一现，找到方法，为遇到这个问题的兄弟避坑：官方ali2115.txt文件里面最后一句dir_id=0就是转存目录，默认是0，也就是根目录，只需要设置为我的接收的目录ID即可。

**Comment by zachang2480592** [comment]
那么问题来了，我的接收的目录ID在哪查看呢？

**Comment by zachang2480592** [comment]
找到了，115浏览器地址栏有
