### ISSUE TITLE
opentoken_url.txt 中 https://api.xhofe.top/alist/ali_open/token 不能修改吗？

### ISSUE THREAD

**Issue by lukemin** [DDS-Derek/xiaoya-alist#192]
opentoken_url.txt 中 https://api.xhofe.top/alist/ali_open/token 不能修改吗？
现在需要替换为https://www.voicehub.top/oauth/alipan，但是每次重启之后又给修改回来了。用的xiaoya host模式。

**Comment by zxjuner** [comment]
xiaoya 原版好像不能修改的，如果用的是 [xiaoya-alist] 可以配置，在 配置 - 高级设置 里可以修改

**Comment by lukemin** [comment]
实测可以修改，要把原来的文件删除，运行fuckaliyun就自动建立了。

**Comment by beijiahiddink** [comment]
> 实测可以修改，要把原来的文件删除，运行fuckaliyun就自动建立了。

这个操作能具体一点吗

**Comment by xianxixi** [comment]
> 实测可以修改，要把原来的文件删除，运行fuckaliyun就自动建立了。

我试了下自动建立的应该是还原来的，里面的URL还是官方的，不过运行了fuckaliyun之后，就能正常访问了。不知道什么原理。

**Comment by xianxixi** [comment]
又想了下，怀疑是docker中的URL文件把外头的文件给覆盖了，于是删了docker中的URL文件，发现外头的文件不能改了，猜测，这个文件本来就是自动生成，且不能改的？

**Comment by yguangg** [comment]
出现了同样的问题，贴主神龙见首不见尾，fuckaliyun 也不知道是啥东东，一番操作后，找到变通解决方案：
在docker模版中增加一个路径映射，将外部文件夹中的 opentoken_url.txt 文件映射到容器内部的 /data/opentoken_url.txt 并设置“只读”属性（-v /path/to/local/opentoken_url.txt : /data/opentoken_url.txt : ro），这样修改后就不会自动还原了，测试一切恢复正常。
