### ISSUE TITLE
极空间获得ssh后用命令一直卡[INFO] 设置 Docker 镜像源中...

### ISSUE THREAD

**Issue by tmzg0000** [DDS-Derek/xiaoya-alist#195]
上周还能正常使用 ，今天用就一直
 [INFO] 设置 Docker 镜像源中...
感觉是获取不到极空间的 image_mirror.txt
我手动执行 all_in_one.sh 并 自己建立 image_mirror.txt 后才能运行

**Comment by XinZhanhua** [comment]
大佬，问一下具体是啥意思呀，我的运行也卡在了设置 Docker 镜像源中，不知道啥情况，怎么解决
