### ISSUE TITLE
提几个需求吧。。。。。。

### ISSUE THREAD

**Issue by duckeaty** [DDS-Derek/xiaoya-alist#2]
安装：
1。指定媒体库目录和配置文件目录（最好生成记录文件，下次用的时候可以提示是否更换或者安装其它功能的时候可以直接调用）
2。可以选择是否安装emby

其它：
1。增加strm中的IP地址替换功能，提示键入错误的IP和正确的IP，同时对DOCKER_ADDRESS字样进行替换
2。增加更改token,emby_server等等之类的设置文件的功能
3。端口禁用的功能，提示正确IP（可更改）和端口（可更改）并配置IPV4和IPV6的禁用端口规则（生成时查询是否已经存在，先删除再添加），并记录，后期可取消禁用。
4。定时任务（xiaoya_keeper,更新替换library.db*）之类的功能。

其它的想到再提。。。

**Comment by duckeaty** [comment]
另外，看看能不能在2345里增加一个选项，不反代直接正常播放，这样可以用硬解。就是可以直链也可以硬解。看能不能实现。

**Comment by DDSDerek** [comment]
done https://github.com/DDS-Derek/xiaoya-alist/issues/7
