### ISSUE TITLE
安装emby其他版本失败

### ISSUE THREAD

**Issue by shay1632022** [DDS-Derek/xiaoya-alist#21]
您好，我安装了一键emby全家桶之后，准备卸载emby安装lovechen版本失败。
我的操作：
1.卸载emby全家桶，删除配置文件y
2.启动一键脚本23
3.没有选择版本的选项，直接跳转到安装
4.脚本提示我xiaoya文件夹和媒体库文件夹，随即安装emby直至完成，期间没有版本选项

**Comment by samqin123** [comment]
我也是出现安装后localhost:2345无法打开，需要手工修改embyserver_config.txt吗？修改内容是http://172.17.0.1:8096？
