### ISSUE TITLE
更新115清理助手后报错

### ISSUE THREAD

**Issue by langoyb** [DDS-Derek/xiaoya-alist#214]
之前是正常的，今天更新后报错如下，用一键脚本卸载重装，按照readme里面写的新建115_cleaner_auto_set_ali2115.txt文件还是不行，不知道哪里操作失误。

2024/10/01 12:48:04 | stderr | AttributeError: 'P115FileSystem' object has no attribute 'fs_batch_delete'
2024/10/01 12:48:04 | stderr | File "115_cleaner.py", line 157, in clear_general_files
2024/10/01 12:48:04 | stderr | File "115_cleaner.py", line 204, in clear_files
2024/10/01 12:48:04 | stderr | File "115_cleaner.py", line 274, in <module>
2024/10/01 12:48:04 | stderr | Traceback (most recent call last):
2024/10/01 12:48:04 | stderr | 2024-10-01 12:48:04,176 - INFO - 115网盘清理助手已关闭
2024/10/01 12:48:03 | stderr | 2024-10-01 12:48:03,824 - INFO - 开始清理转存文件（标准模式）
2024/10/01 12:48:03 | stderr | 2024-10-01 12:48:03,589 - INFO - 115网盘清理助手运行中...
2024/10/01 12:47:02 | stderr | [PYI-7:ERROR] Failed to execute script '115_cleaner' due to unhandled exception!
2024/10/01 12:47:02 | stderr | AttributeError: 'P115FileSystem' object has no attribute 'fs_batch_delete'
2024/10/01 12:47:02 | stderr | File "115_cleaner.py", line 157, in clear_general_files
2024/10/01 12:47:02 | stderr | File "115_cleaner.py", line 204, in clear_files
2024/10/01 12:47:02 | stderr | File "115_cleaner.py", line 274, in <module>
2024/10/01 12:47:02 | stderr | Traceback (most recent call last):
2024/10/01 12:47:02 | stderr | 2024-10-01 12:47:02,277 - INFO - 115网盘清理助手已关闭
2024/10/01 12:47:01 | stderr | 2024-10-01 12:47:01,966 - INFO - 开始清理转存文件（标准模式）
2024/10/01 12:47:01 | stderr | 2024-10-01 12:47:01,729 - INFO - 115网盘清理助手运行中...

**Comment by DDSDerek** [comment]
已修复，请更新 115 Cleaner

**Comment by langoyb** [comment]
感谢大佬及时修复，这下正常了。
