### ISSUE TITLE
一键安装emby脚本报错请检查xiaoya是否正常运行后再试

### ISSUE THREAD

**Issue by ymxl9769** [DDS-Derek/xiaoya-alist#22]
运行环境是黑群晖，用一键脚本搭建的xiaoya-tvbox，网页端和webdave正常运行播放，但是用安装脚本一键安装emby就会报错
![image](https://github.com/DDS-Derek/xiaoya-alist/assets/55675521/2cc4f4d0-de2f-4ac9-956c-248c9aae262a)

**Comment by DDSDerek** [comment]
目前暂时不支持xiaoya-tvbox部署全家桶，只能通过官方小雅容器来部署全家桶
