### ISSUE TITLE
一键脚本可否增加V2rayA部署的一键脚本？因为小雅容器的安装需要翻墙，否则容易出现问题。

### ISSUE THREAD

**Issue by tawangxunyuan** [DDS-Derek/xiaoya-alist#223]
小雅容器的部署的前提是需要翻墙，目前很多跟我一样的小白经常卡在这一步，导致安装失败，所以恳求高中生朋友帮帮忙把这个V2rayA或者其它类似的翻墙的容器也搞一个一键脚本，就把短板补上了！多谢

**Comment by lordyoung1221** [comment]
不需要翻墙，脚本9、6测试源，哪个快用哪个。

**Comment by tawangxunyuan** [comment]
不翻墙后期没法使用啊。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月21日 16:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [DDS-Derek/xiaoya-alist] 一键脚本可否增加V2rayA部署的一键脚本？因为小雅容器的安装需要翻墙，否则容易出现问题。 (Issue #223) |

经常卡住，而且不翻墙，安装完也不能更新，小雅明确需要翻墙了。

**Comment by tawangxunyuan** [comment]
明着说吧，不支持这个功能的原因是因为国内不允许么？有法律风险当面的考虑？否则真的搞不明白为啥不完善这个功能



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月17日 12:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [DDS-Derek/xiaoya-alist] 一键脚本可否增加V2rayA部署的一键脚本？因为小雅容器的安装需要翻墙，否则容易出现问题。 (Issue #223) |

Closed #223 as not planned.
