### ISSUE TITLE
提示Parse error near line 1: no such table: x_storages

### ISSUE THREAD

**Issue by miraclesweetheart** [DDS-Derek/xiaoya-alist#228]
Parse error near line 1: no such table: x_storages

**Comment by lucienhsu** [comment]
有效地址为：https://fastly.jsdelivr.net/gh/xiaoyaliu00/data@latest
数据版本已经是最新的无须更新
[update.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of update.zip or
        update.zip.zip, and cannot find update.zip.ZIP, period.
sed: update.sql: No such file or directory
sed: update.sql: No such file or directory
/data/pikpak.txt: No such file or directory (os error 2)
sed: update.sql: No such file or directory
Error: cannot open "update.sql"
cp: can't stat 'opentoken_url.txt': No such file or directory
rm: can't remove 'update.sql': No such file or directory
rm: can't remove 'opentoken_url.txt': No such file or directory
Parse error near line 1: no such table: x_storages
 records have been updated into your database
[/tmp/tvbox.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/tvbox.zip or
        /tmp/tvbox.zip.zip, and cannot find /tmp/tvbox.zip.ZIP, period.
sed: /www/tvbox/my.json: No such file or directory
sed: /www/tvbox/json/alist.json: No such file or directory
sed: /www/tvbox/json/myalist.json: No such file or directory
sed: /www/tvbox/juhe.json: No such file or directory
Parse error near line 1: no such table: x_setting_items
sed: /www/tvbox/libs/alist.min.js: No such file or directory
sed: /www/tvbox/cat/libs/cat.alist.min.js: No such file or directory
sed: /www/tvbox/libs/alist.min.js: No such file or directory
[index.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of index.zip or
        index.zip.zip, and cannot find index.zip.ZIP, period.
cat: can't open 'index.pikpak.txt': No such file or directory
cat: can't open 'index.book.txt': No such file or directory
cat: can't open 'index.music.txt': No such file or directory
cat: can't open 'index.non.video.txt': No such file or directory
Thu Oct 17 12:48:00 CST 2024 User's own token xxxxxxxxxxxxxxxxxx has been updated into database successfully
Parse error near line 1: no such table: x_storages
Parse error near line 1: no such table: x_storages
Parse error near line 2: no such table: x_storages
Parse error near line 3: no such table: x_storages
Parse error near line 4: no such table: x_storages
Parse error near line 5: no such table: x_storages
Parse error near line 6: no such table: x_storages
Parse error near line 7: no such table: x_storages
Parse error near line 8: no such table: x_storages
Parse error near line 9: no such table: x_storages
Parse error near line 1: no such table: x_storages
Parse error near line 1: no such table: x_storages
Parse error near line 1: no such table: x_storages
Parse error near line 2: no such table: x_storages
Parse error near line 1: no such table: x_storages
Parse error near line 1: no such table: x_storages
Parse error near line 1: no such table: x_storages
启动容器(Bridge模式)......
INFO[2024-10-17 12:48:10] reading config file: data/config.json        
INFO[2024-10-17 12:48:10] load config from env with prefix:            
INFO[2024-10-17 12:48:10] init logrus...                               
INFO[2024-10-17 12:48:10] start server @ 127.0.0.1:5244

**Comment by wanghc02** [comment]
同样的错误，解决没有？

**Comment by lucienhsu** [comment]
> 同样的错误，解决没有？

解决

**Comment by wanghc02** [comment]
> > 同样的错误，解决没有？
> 
> 解决

咋解决的？

**Comment by ChurchTao** [comment]
怎么解决的
