### ISSUE TITLE
Windows WSL Docker 支持全家桶脚本

### ISSUE THREAD

**Issue by Nobbyte** [DDS-Derek/xiaoya-alist#230]
### 下面以 **WSL Ubuntu** 和 **Docker Desktop** 为例

- WSL2 下安装 Ubuntu
- Docker Desktop设置 `Resources -> WSL integration` 选中 Ubuntu 保存
- 打开 Ubuntu 终端 `sudo -i `切换到root即可执行全家桶脚本

### **Tips**

Ubuntu可直接访问Windows的文件
比如C盘就是`/mnt/c/`
可在Windows本地创建目录映射到容器中

例：
在E盘创建xiaoya文件夹
安装小雅目录可设置为 `/mnt/e/xiaoya/alist`
Emby全家桶挂载目录不能设置win盘 直接使用系统目录

### **Warn**
安装时不要选择扫码添加Token，会出现端口打不开的情况
对于fuckaliyun (转换tv端token) 可以选择手动运行容器
### **fuckaliyun**
```
docker run -d \
  --name aliyuntvtoken \
  --publish 34256:34256 \
  --env LANG=C.UTF-8 \
  --volume /mnt/e/your_xiaoya:/data \
  --net default \
  ddsderek/xiaoya-glue:python /aliyuntvtoken/alitoken2.py
```

**Comment by wlrwx** [comment]
我也是这么搞的，之前没安装emby一切正常，解压了一天的emby，现在localhost也打不开了，127.0.0.1也打不开了，192.168.x.x也打不开了，哎……

**Comment by wlrwx** [comment]
强烈建议fuckaliyun可以选择手动填写aliyuntvtokun。

**Comment by DDSDerek** [comment]
目前扫码容器可以去高级配置里面选择使用bridge网络模式，理论上可以正常使用扫码了，感谢提出解决方法！
