### ISSUE TITLE
安装jellyfin时 config_jf.mp4下载不完整

### ISSUE THREAD

**Issue by Plaudern** [DDS-Derek/xiaoya-alist#239]
![image](https://github.com/user-attachments/assets/f93fb623-0a41-47bb-90ed-ccb32d9b9221)
报错如图，我看到有人提了这个错时阿里云盘空间不足，可是我阿里云盘还有4个T
![image](https://github.com/user-attachments/assets/b8c80982-793d-4d34-bd2b-0d3d1a1ad892)

**Comment by DDSDerek** [comment]
如果您需要安装 小雅Jellyfin 全家桶，请使用 AI老G 的脚本安装，风险自担。
脚本命令：bash <(curl -sSLf https://xy.ggbond.org/xy/xy_install.sh)
