### ISSUE TITLE
一键安装emby脚本报错请检查xiaoya是否正常运行后再试

### ISSUE THREAD

**Issue by wolfling45** [DDS-Derek/xiaoya-alist#25]
运行环境是unraid，使用脚本搭建的xiaoya，bridge模式，访问一切正常，docker_address.txt也配置正确
![屏幕截图 2024-03-04 193001](https://github.com/DDS-Derek/xiaoya-alist/assets/5054806/c58d7f89-970b-4beb-a58a-fe31f735d61d)
![屏幕截图 2024-03-04 204010](https://github.com/DDS-Derek/xiaoya-alist/assets/5054806/f9e4773f-1320-445e-850f-2638c24b189e)

**Comment by wolfling45** [comment]
抱歉，是我自己的问题，已经解决。

**Comment by xuekuangyi** [comment]
我遇到了同样的问题，到底啥原因？

**Comment by dikevin0512** [comment]
您倒是说说怎么解决的啊！

**Comment by junyuyuan** [comment]
咋解决的？我这也是同样的问题
![image](https://github.com/DDS-Derek/xiaoya-alist/assets/11531378/4080d8db-41ac-4729-bfc5-a0529f44a18e)

**Comment by dikevin0512** [comment]
> 咋解决的？我这也是同样的问题 ![image](https://private-user-images.githubusercontent.com/11531378/334263322-4080d8db-41ac-4729-bfc5-a0529f44a18e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4Njk3MjAsIm5iZiI6MTcxNjg2OTQyMCwicGF0aCI6Ii8xMTUzMTM3OC8zMzQyNjMzMjItNDA4MGQ4ZGItNDFhYy00NzI5LWJmYzUtYTA1MjlmNDRhMThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA0MTAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5YzEzZDcwZDAwYWMyODYxNmFjMTc3NTYwYmYxOTEzZmZlMGY1MmI1ZjU0MmRmODkzOGUzMjU4MGUzYjljYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ACU6lsu-_WjIOlM9t8diWsa1y982sYpNsn7KVaNUh6A)

不断重启还token,换完token要等一段时间，自己就好了，也不知道具体原因

**Comment by junyuyuan** [comment]
确实，还挺奇怪的，我没重启换token，中午休息了俩小时，然后再安装emby一键就好了。。。

**Comment by shenzt68** [comment]
<img width="190" alt="Image" src="https://github.com/user-attachments/assets/de2d7ee8-9e5c-4faa-a794-e5234547c309" />
你们的xiaoya可以管理吗？
我在本地找不到脚本安装好xiaoya后，它的模板。
无法安装emby
