### ISSUE TITLE
重新获取更换115秘钥，还是提示错误

### ISSUE THREAD

**Issue by a429407740** [DDS-Derek/xiaoya-alist#255]
{"state":false,"error":"请重新登录","errno":99,"request":"\/app\/share\/downurl?t=1734662218","data":[]}: user not login

**Comment by xjEthan** [comment]
bash -c "$(curl --insecure -fsSL https://ddsrem.com/xiaoya_install.sh)"我是 执行 1 2 更新一下就好了

**Comment by a429407740** [comment]
> bash -c "$(curl --insecure -fsSL [https://ddsrem.com/xiaoya_install.sh)"我是](https://ddsrem.com/xiaoya_install.sh)%22%E6%88%91%E6%98%AF) 执行 1 2 更新一下就好了

昨天看到镜像升级，也升级，可以了
