### ISSUE TITLE
部署115cleaner之后， 创建并获取 我的接收 文件夹ID失败，请手动配置 ali2115.txt 文件！

### ISSUE THREAD

**Issue by wwy0201** [DDS-Derek/xiaoya-alist#259]
ali2115.text如下
purge_ali_temp=true
cookie="正确的cookie"
purge_pan115_temp=true
dir_id="251824024840283135"

查看115cleaner docker 日志如下
2024-12-24 17:49:20,085 - INFO - 115网盘清理助手运行中...
2024-12-24 17:49:20,085 - INFO - 自动配置 ali2115 文件中...
2024-12-24 17:49:20,233 - INFO - HTTP Request: GET http://proapi.115.com/android/2.0/ufile/files?aid=1&count_folders=1&limit=1000&offset=0&record_open_time=1&show_dir=1&cid=0&custom_order=1&o=file_name&asc=1&fc_mix=0 "HTTP/1.1 200 OK"
2024-12-24 17:49:20,266 - INFO - HTTP Request: GET http://webapi.115.com/files/getid?path=%2F%E6%88%91%E7%9A%84%E6%8E%A5%E6%94%B6 "HTTP/1.1 200 OK"
2024-12-24 17:49:20,266 - ERROR - 创建并获取 我的接收 文件夹ID失败，请手动配置 ali2115.txt 文件！

**Comment by ZhuFengZhe9009** [comment]
我也遇到这样的问题 坐等大佬

**Comment by wwy0201** [comment]
> 我也遇到这样的问题 坐等大佬

问题已经解决了，你更新115cleaner的docker镜像或者再安装一次就行了

**Comment by ZhuFengZhe9009** [comment]
<html>
<body>

2024/12/31 09:32:17 | stderr | 2024-12-31 09:32:17,898 - ERROR - 请手动配置 ali2115.txt 文件！
-- | -- | --
2024/12/31 09:32:17 | stderr | 2024-12-31 09:32:17,898 - ERROR - 创建并获取 我的接收 文件夹ID失败：[Errno 17] '我的接收' (in 3064888108938649465) already exists
2024/12/31 09:32:17 | stderr | 2024-12-31 09:32:17,898 - INFO - HTTP Request: GET http://anxia.com/webapi/files/get_info?file_id=3064888108938649465 "HTTP/1.1 200 OK"
2024/12/31 09:32:17 | stderr | 2024-12-31 09:32:17,783 - INFO - HTTP Request: GET http://webapi.115.com/files/getid?path=%2F%E6%88%91%E7%9A%84%E6%8E%A5%E6%94%B6 "HTTP/1.1 200 OK"
2024/12/31 09:32:17 | stderr | 2024-12-31 09:32:17,706 - INFO - HTTP Request: GET http://proapi.115.com/android/2.0/ufile/files?aid=1&count_folders=1&limit=1000&offset=0&record_open_time=1&show_dir=1&cid=0&custom_order=1&o=file_name&asc=1&fc_mix=0 "HTTP/1.1 200 OK"
2024/12/31 09:32:17 | stderr | 2024-12-31 09:32:17,538 - INFO - 自动配置 ali2115 文件中...
2024/12/31 09:32:17 | stderr | 2024-12-31 09:32:17,538 - INFO - 115网盘清理助手运行中...


</body>
</html>

**Comment by DDSDerek** [comment]
> 2024/12/31 09:32:17 | stderr | 2024-12-31 09:32:17,898 - ERROR - 请手动配置 ali2115.txt 文件！ -- | -- | -- 2024/12/31 09:32:17 | stderr | 2024-12-31 09:32:17,898 - ERROR - 创建并获取 我的接收 文件夹ID失败：[Errno 17] '我的接收' (in 3064888108938649465) already exists 2024/12/31 09:32:17 | stderr | 2024-12-31 09:32:17,898 - INFO - HTTP Request: GET http://anxia.com/webapi/files/get_info?file_id=3064888108938649465 "HTTP/1.1 200 OK" 2024/12/31 09:32:17 | stderr | 2024-12-31 09:32:17,783 - INFO - HTTP Request: GET http://webapi.115.com/files/getid?path=%2F%E6%88%91%E7%9A%84%E6%8E%A5%E6%94%B6 "HTTP/1.1 200 OK" 2024/12/31 09:32:17 | stderr | 2024-12-31 09:32:17,706 - INFO - HTTP Request: GET http://proapi.115.com/android/2.0/ufile/files?aid=1&count_folders=1&limit=1000&offset=0&record_open_time=1&show_dir=1&cid=0&custom_order=1&o=file_name&asc=1&fc_mix=0 "HTTP/1.1 200 OK" 2024/12/31 09:32:17 | stderr | 2024-12-31 09:32:17,538 - INFO - 自动配置 ali2115 文件中... 2024/12/31 09:32:17 | stderr | 2024-12-31 09:32:17,538 - INFO - 115网盘清理助手运行中... 还是不可以

再次更新，然后发日志

**Comment by ZhuFengZhe9009** [comment]
<html>
<body>
<h2 style="text-align: center; color: rgb(0, 0, 0); font-family: &quot;Lucida Console&quot;, Consola, Monaco, monospace, &quot;Courier New&quot;, Courier, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">xiaoya-115cleaner</h2>
date | stream | content
-- | -- | --
2025/01/02 09:03:54 | stderr | 2025-01-02 09:03:54,512 - ERROR - 获取 我的接收 文件夹文件列表失败：[Errno 5] {'state': False, 'error': '请重新登录', 'errno': 99, 'request': '/android/2.0/ufile/files?aid=1&count_folders=1&limit=1000&offset=0&record_open_time=1&show_dir=1&cid=3066865919928786820&custom_order=1&o=file_name&asc=1&fc_mix=0', 'data': []}
2025/01/02 09:03:54 | stderr | 2025-01-02 09:03:54,511 - INFO - HTTP Request: GET http://proapi.115.com/android/2.0/ufile/files?aid=1&count_folders=1&limit=1000&offset=0&record_open_time=1&show_dir=1&cid=3066865919928786820&custom_order=1&o=file_name&asc=1&fc_mix=0 "HTTP/1.1 200 OK"
2025/01/02 09:03:54 | stderr | 2025-01-02 09:03:54,435 - INFO - HTTP Request: GET http://anxia.com/webapi/files/get_info?file_id=3066865919928786820 "HTTP/1.1 200 OK"
2025/01/02 09:03:54 | stderr | 2025-01-02 09:03:54,315 - INFO - HTTP Request: GET http://webapi.115.com/files/getid?path=%2F%E6%88%91%E7%9A%84%E6%8E%A5%E6%94%B6 "HTTP/1.1 200 OK"
2025/01/02 09:03:54 | stderr | 2025-01-02 09:03:54,181 - INFO - 开始清理转存文件（标准模式）
2025/01/02 09:03:53 | stderr | 2025-01-02 09:03:53,986 - INFO - 115网盘清理助手运行中...


</body>
</html>

**Comment by ZhuFengZhe9009** [comment]
<html>
<body>

date | stream | content
-- | -- | --
2025/01/06 09:06:06 | stderr | 2025-01-06 09:06:06,222 - ERROR - 获取 我的接收 文件夹文件列表失败：[Errno 5] {'state': False, 'error': '请重新登录', 'errno': 99, 'request': '/android/2.0/ufile/files?aid=1&count_folders=1&limit=1000&offset=0&record_open_time=1&show_dir=1&cid=3071149631742893375&custom_order=1&o=file_name&asc=1&fc_mix=0', 'data': []}
2025/01/06 09:06:06 | stderr | 2025-01-06 09:06:06,221 - INFO - HTTP Request: GET http://proapi.115.com/android/2.0/ufile/files?aid=1&count_folders=1&limit=1000&offset=0&record_open_time=1&show_dir=1&cid=3071149631742893375&custom_order=1&o=file_name&asc=1&fc_mix=0 "HTTP/1.1 200 OK"
2025/01/06 09:06:06 | stderr | 2025-01-06 09:06:06,152 - INFO - HTTP Request: GET http://webapi.115.com/files/get_info?file_id=3071149631742893375 "HTTP/1.1 200 OK"
2025/01/06 09:06:06 | stderr | 2025-01-06 09:06:06,110 - INFO - HTTP Request: GET http://webapi.115.com/files/getid?path=%2F%E6%88%91%E7%9A%84%E6%8E%A5%E6%94%B6 "HTTP/1.1 200 OK"
2025/01/06 09:06:06 | stderr | 2025-01-06 09:06:06,022 - INFO - 开始清理转存文件（标准模式）
2025/01/06 09:06:05 | stderr | 2025-01-06 09:06:05,835 - INFO - ali2115.txt 文件更新成功！
2025/01/06 09:06:05 | stderr | 2025-01-06 09:06:05,835 - INFO - 获取到 我的接收 文件夹ID为 3071149631742893375
2025/01/06 09:06:05 | stderr | 2025-01-06 09:06:05,834 - INFO - HTTP Request: GET http://anxia.com/webapi/files/get_info?file_id=3071149631742893375 "HTTP/1.1 200 OK"
2025/01/06 09:06:05 | stderr | 2025-01-06 09:06:05,724 - INFO - HTTP Request: POST http://webapi.115.com/files/add "HTTP/1.1 200 OK"
2025/01/06 09:06:05 | stderr | 2025-01-06 09:06:05,680 - INFO - HTTP Request: GET http://webapi.115.com/files/getid?path=%2F%E6%88%91%E7%9A%84%E6%8E%A5%E6%94%B6 "HTTP/1.1 200 OK"
2025/01/06 09:06:05 | stderr | 2025-01-06 09:06:05,612 - INFO - 根目录无任何文件，创建 我的接收 文件夹中...
2025/01/06 09:06:05 | stderr | 2025-01-06 09:06:05,600 - INFO - HTTP Request: GET http://proapi.115.com/android/2.0/ufile/files?aid=1&count_folders=1&limit=1000&offset=0&record_open_time=1&show_dir=1&cid=0&custom_order=1&o=file_name&asc=1&fc_mix=0 "HTTP/1.1 200 OK"
2025/01/06 09:06:05 | stderr | 2025-01-06 09:06:05,450 - INFO - 自动配置 ali2115 文件中...
2025/01/06 09:06:05 | stderr | 2025-01-06 09:06:05,449 - INFO - 115网盘清理助手运行中...


</body>
</html>
