### ISSUE TITLE
小雅助手无法正常工作

### ISSUE THREAD

**Issue by wolfling45** [DDS-Derek/xiaoya-alist#31]
fetch https://mirrors.nju.edu.cn/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.nju.edu.cn/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
(1/2) Installing ca-certificates (20230506-r0)
(2/2) Installing docker-cli (25.0.3-r0)
Executing busybox-1.36.1-r0.trigger
Executing ca-certificates-20230506-r0.trigger
OK: 33 MiB in 17 packages
(1/6) Installing brotli-libs (1.0.9-r14)
(2/6) Installing libunistring (1.1-r1)
(3/6) Installing libidn2 (2.3.4-r1)
(4/6) Installing nghttp2-libs (1.57.0-r0)
(5/6) Installing libcurl (8.5.0-r0)
(6/6) Installing curl (8.5.0-r0)
Executing busybox-1.36.1-r0.trigger
OK: 37 MiB in 23 packages
(1/1) Installing tzdata (2024a-r0)
OK: 40 MiB in 24 packages
[2024/03/14 16:59:49]小雅缓存清理(ver=202402190042)运行中
cat: can't open '/data/mytoken.txt': No such file or directory
cat: can't open '/data/mytoken.txt': No such file or directory
#Failed to execute command "get_Header", retrying in 1 seconds (retry 1 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 2 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 3 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 4 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 5 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 6 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 7 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 8 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 9 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 10 of 10)...
#Failed to execute command after 10 retries: get_Header
#Command output: 获取drive_id失败
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 1 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 2 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 3 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 4 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 5 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 6 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 7 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 8 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 9 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 10 of 10)...
#Failed to execute command after 10 retries: get_rawList 0
#Command output: 获取文件列表失败：folder_id=,drive_id=

我在容器中手动执行下面的命令是可以读取的
![微信图片_20240314170359](https://github.com/DDS-Derek/xiaoya-alist/assets/5054806/5ae115ab-36f3-4966-8c2b-6c8855e34dad)

**Comment by DDSDerek** [comment]
不用理会，阿里云限流，过几天就正常了

**Comment by lolipoi** [comment]
我也是遇到这个问题，等待解决方法中....

**Comment by lolipoi** [comment]
小雅助手无法清理文件可以尝试切换阿里盘挂载类型，文件是folder_type.txt，如果是r就改成b，反之亦然
r是资源盘，b是备份盘
