### ISSUE TITLE
小雅Emby全家桶 解压全部元数据 报错 408

### ISSUE THREAD

**Issue by zhoubuhong** [DDS-Derek/xiaoya-alist#34]
小雅Emby全家桶 解压全部元数据会报错，错误码：408

命令：bash -c "$(curl -sLk https://ddsrem.com/xiaoya_install.sh)"

单独 解压 全部元数据 -> 2 2 2

小雅服务没有问题，小雅我可以浏览

![error](https://github.com/DDS-Derek/xiaoya-alist/assets/85562985/8c4d8a8c-23f0-4e5f-af0f-3eb7cb0b5706)

**Comment by zhoubuhong** [comment]
求助，这个是怎么回事，该如何解决呢 /哭死

**Comment by DDSDerek** [comment]
应该是网络问题
