### ISSUE TITLE
小雅alis阿里云转存问题

### ISSUE THREAD

**Issue by chyaww** [DDS-Derek/xiaoya-alist#36]
大佬，安装好Alist后，所有打开的文件都会转存到阿里云小雅转存文件夹内导致阿里云撑满，导致后续文件无法转存，出现“获取新file id失败”，这个怎么解决？

**Comment by chyaww** [comment]
使用模式5：与模式3的区别是实时清理，只要产生了播放缓存一分钟内立即清理。签到和定时升级同模式3
bash -c "$(curl -s https://xiaoyahelper.zngle.cf/aliyun_clear.sh | tail -n +2)" -s 5
发现xiaoyakeeper报错：
#Failed to execute command "get_Header", retrying in 1 seconds (retry 1 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 2 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 3 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 4 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 5 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 6 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 7 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 8 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 9 of 10)...
#Failed to execute command "get_Header", retrying in 1 seconds (retry 10 of 10)...
#Failed to execute command after 10 retries: get_Header
#Command output: 获取drive_id失败
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 1 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 2 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 3 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 4 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 5 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 6 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 7 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 8 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 9 of 10)...
#Failed to execute command "get_rawList", retrying in 1 seconds (retry 10 of 10)...
#Failed to execute command after 10 retries: get_rawList 0
#Command output: 获取文件列表失败：folder_id=65f7078875ba9194aff04xxxx,drive_id=

**Comment by chyaww** [comment]
测试了下，发现脚本aliyun_clear.sh中函数get_Header()中的https://api.aliyundrive.com/v2/account/token 无法打开

**Comment by DDSDerek** [comment]
大概率是被阿里云限流了，或者说网络问题
