### ISSUE TITLE
一键Emby脚本安装提示：获取新file id失败。请问怎么解决？试过更换ip

### ISSUE THREAD

**Issue by QingYan1012** [DDS-Derek/xiaoya-alist#37]
![微信图片_20240321225954](https://github.com/DDS-Derek/xiaoya-alist/assets/11241476/555b85f2-1fc4-4a4d-ad48-80e8207dd93f)

**Comment by xianweibo** [comment]
同问，怎么解决

**Comment by DDSDerek** [comment]
更新token和fileid

**Comment by Angel0726** [comment]
> 更新token和fileid

需要经常更换tokenid吗
