### ISSUE TITLE
openwrt的resilio启动失败

### ISSUE THREAD

**Issue by kufei326** [DDS-Derek/xiaoya-alist#38]
INFO] 系统 inotify watches 数值已存在！
[INFO] 系统 inotify instances 数值已存在！
sysctl: error setting key 'fs.inotify.max_user_watches': Read-only file system
sysctl: error setting key 'fs.inotify.max_user_instances': Read-only file system
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
5ca8d8283e576973c91b6e033f7e1a43216cf072d3fe48f69a7ccffc04cc39b7
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: openat2 /sys/fs/cgroup/docker/5ca8d8283e576973c91b6e033f7e1a43216cf072d3fe48f69a7ccffc04cc39b7/memory.max: no such file or directory: unknown.

**Comment by DDSDerek** [comment]
你的openwrt内核太老，不支持限制resilio容器内存

**Comment by kufei326** [comment]
> 你的openwrt内核太老，不支持限制resilio容器内存

6.1.82最新的内核
