### ISSUE TITLE
小雅alist只有版本号，没有资源列表，请问怎么解决谢谢！

### ISSUE THREAD

**Issue by zhangteng1991** [DDS-Derek/xiaoya-alist#42]
日志如下：
rm: can't remove '*.zip': No such file or directory

sh: exists: unknown operand

无法连接CloudFlare服务器

Connecting to docker.xiaoya.pro (104.21.17.247:80)

saving to 'version.txt'

version.txt          100% |*******************************************************************************************************************************************************************************************************************************************************************************************************************|     7  0:00:00 ETA

'version.txt' saved

Connecting to docker.xiaoya.pro (104.21.17.247:80)

Connecting to raw.githubusercontent.com (185.199.109.133:443)

wget: download timed out

Failed to download update database file, the database upgrade process has aborted

Connecting to docker.xiaoya.pro (104.21.17.247:80)

Connecting to raw.githubusercontent.com (185.199.109.133:443)

wget: download timed out

unzip:  cannot find or open tvbox.zip, tvbox.zip.zip or tvbox.zip.ZIP.

rm: can't remove 'tvbox.zip': No such file or directory

sed: /www/tvbox/my.json: No such file or directory

sed: /www/tvbox/json/alist.json: No such file or directory

sed: /www/tvbox/json/myalist.json: No such file or directory

sed: /www/tvbox/juhe.json: No such file or directory

sed: /www/tvbox/libs/alist.min.js: No such file or directory

sed: /www/tvbox/cat/libs/cat.alist.min.js: No such file or directory

sed: /www/tvbox/libs/alist.min.js: No such file or directory

最新数据版本：0.8.47

Tue Apr 9 18:33:16 CST 2024 current index file version is updated, no need to upgrade

Tue Apr 9 18:33:17 CST 2024 User's own token a9ebae6f95d646489a51fc99f42e0d51 has been updated into database successfully

**Comment by chenzao1024** [comment]
一样的问题

**Comment by damoye** [comment]
同样的问题，不过我这边报的503错误：
```
INFO[2024-04-10 09:42:39] reading config file: data/config.json        
INFO[2024-04-10 09:42:39] load config from env with prefix:            
INFO[2024-04-10 09:42:39] init logrus...                               
INFO[2024-04-10 09:42:39] start server @ 127.0.0.1:5234                
INFO[2024-04-10 09:42:39] success load storage: [/©️ v.0410.0002(H)], driver: [UrlTree] 
rm: can't remove '*.zip': No such file or directory
Connecting to docker.xiaoya.pro (172.67.178.229:80)
wget: server returned error: HTTP/1.1 503 Service Unavailable
Failed to download version.txt file, the index file upgrade process has aborted
Connecting to docker.xiaoya.pro (172.67.178.229:80)
Connecting to cdn.jsdelivr.net (46.82.174.69:443)
wget: download timed out
unzip:  cannot find or open tvbox.zip, tvbox.zip.zip or tvbox.zip.ZIP.
rm: can't remove 'tvbox.zip': No such file or directory
sed: /www/tvbox/my_ext.json: No such file or directory
sed: /www/tvbox/juhe_ext.json: No such file or directory
sed: /www/tvbox/json/alist_ext.json: No such file or directory
sed: /www/tvbox/my.json: No such file or directory
sed: /www/tvbox/json/alist.json: No such file or directory
sed: /www/tvbox/json/myalist.json: No such file or directory
sed: /www/tvbox/juhe.json: No such file or directory
sed: /www/tvbox/libs/alist.min.js: No such file or directory
sed: /www/tvbox/cat/libs/cat.alist.min.js: No such file or directory
sed: /www/tvbox/libs/alist.min.js: No such file or directory
Failed to download version.txt file, the index file upgrade process has aborted
Wed Apr 10 22:22:42 CST 2024 User's own token 9ecef536eb30489f8c7a63cf48bedd81 has been updated into database successfully
```

**Comment by icysky1** [comment]
docker exec -it xiaoya /updateall
用这个指令多试几次。

看到下面这种无法连接或连接超时的情况就是数据没下载回来，多试几次应该可以，我就试这样解决的，部分地区可能是因为被运营商屏蔽。

无法连接CloudFlare服务器
Connecting to docker.xiaoya.pro (172.67.178.229:80)
saving to 'version.txt'
version.txt          100% |**********************************************************************************************************************************************************************************|     7  0:00:00 ETA
'version.txt' saved
最新数据版本：0.8.48
Connecting to docker.xiaoya.pro (172.67.178.229:80)
Connecting to cdn.jsdelivr.net (8.7.198.46:443)
wget: download timed out
Failed to download update database file, the database upgrade process has aborted

**Comment by hsj01** [comment]
同问题，用了老哥的docker exec -it xiaoya /updateall命令也只能获取到version.txt，其他数据还是下载不下来，我还挂了梯子，也是下载不下来。

rm: can't remove '*.zip': No such file or directory
Connecting to docker.xiaoya.pro (172.67.178.229:80)
saving to 'version.txt'
version.txt          100% |**********************************************************************************|     7  0:00:00 ETA
'version.txt' saved
最新数据版本：0.8.49
Connecting to docker.xiaoya.pro (172.67.178.229:80)
Connecting to cdn.jsdelivr.net (104.16.88.20:443)
wget: server returned error: HTTP/1.1 403 Forbidden
Failed to download update database file, the database upgrade process has aborted
Connecting to docker.xiaoya.pro (172.67.178.229:80)
Connecting to cdn.jsdelivr.net (104.16.85.20:443)
wget: server returned error: HTTP/1.1 403 Forbidden
unzip:  cannot find or open tvbox.zip, tvbox.zip.zip or tvbox.zip.ZIP.
rm: can't remove 'tvbox.zip': No such file or directory
sed: /www/tvbox/my.json: No such file or directory
sed: /www/tvbox/json/alist.json: No such file or directory
sed: /www/tvbox/json/myalist.json: No such file or directory
sed: /www/tvbox/juhe.json: No such file or directory
sed: /www/tvbox/libs/alist.min.js: No such file or directory
sed: /www/tvbox/cat/libs/cat.alist.min.js: No such file or directory
sed: /www/tvbox/libs/alist.min.js: No such file or directory
Thu Apr 11 14:22:26 CST 2024 current index file version is updated, no need to upgrade

**Comment by DDSDerek** [comment]
需要自定义下载地址，自己添加一个  download_url.txt
内容是 除了 update.zip tvbox.zip
（实际地址是 https://raw.githubusercontent.com/xiaoyaliu00/data/main/tvbox.zip 和 https://raw.githubusercontent.com/xiaoyaliu00/data/main/update.zip）

前的url，也就是
https://xxxxxx/https://raw.githubusercontent.com/xiaoyaliu00/data/main/tvbox.zip
那么你就填（不要最后一个 /）
https://xxxxxx/https://raw.githubusercontent.com/xiaoyaliu00/data/main

找了一些测试都可以用
                                                                                                              
https://git.jasonml.xyz
https://cdn.wygg.shop
https://gh.ddlc.top
https://git.886.be
https://gh.idayer.com
https://slink.ltd

**Comment by wangqianyang** [comment]
download_url.txt 这个文件放哪里？所有方法都试了，不行，想采用这个方案试试

**Comment by wangqianyang** [comment]
问题已解决，
download_url.txt 放在 /etc/xiaoya 目录下
文本内容只有一行：
https://raw.githubusercontent.com/xiaoyaliu00/data/main

因为我的服务器可以直接访问github，所以没有加前面的https://xxxxxx/
