### ISSUE TITLE
功能需求：更换library.db后会导致非管理帐户进去后空白，能不能研究下emby的API

### ISSUE THREAD

**Issue by duckeaty** [DDS-Derek/xiaoya-alist#5]
目前需要管理帐户进去在控制台点用户，把其它用户点开都保存一下，就正常了。看能不能研究一下emby的api，弄个脚本在更新library.db后自动执行脚本更新用户策略。参考：
https://swagger.emby.media/?staticview=true#/UserService

**Comment by duckeaty** [comment]
已经解决。

**Comment by DDSDerek** [comment]
https://github.com/DDS-Derek/xiaoya-alist/issues/7
