### ISSUE TITLE
什么时候重新支持amilys

### ISSUE THREAD

**Issue by akang943578** [DDS-Derek/xiaoya-alist#55]
[INFO] 请选择使用的Emby镜像 [ 1:emby/embyserver | 2:lovechen/embyserver(不推荐！目前不能直接同步config数据，且还存在一些已知问题未修复) ]（默认 1）

我记得之前是支持amilys的，现在怎么没有了，何时重新支持？

**Comment by DDSDerek** [comment]
arm64架构无法使用amilys的镜像

**Comment by akang943578** [comment]
> arm64架构无法使用amilys的镜像

是有的，amilys/embyserver_arm64v8:latest 这个是我自己搭建的，用着没有问题，希望可以在脚本里得到支持。

**Comment by DDSDerek** [comment]
> > arm64架构无法使用amilys的镜像
> 
> 是有的，amilys/embyserver_arm64v8:latest 这个是我自己搭建的，用着没有问题，希望可以在脚本里得到支持。

感谢说明，这周末将支持
