### ISSUE TITLE
大佬能否搞一个支持WSL的？

### ISSUE THREAD

**Issue by seekdoor** [DDS-Derek/xiaoya-alist#58]
我的笔记本24H不关机，但是宿主机是Win11，能否增加WSL支持。

感谢！

**Comment by DDSDerek** [comment]
目前不考虑，可以自己手动安装

**Comment by yyyyyyounger** [comment]
> 我的笔记本24H不关机，但是宿主机是Win11，能否增加WSL支持。
> 
> 感谢！

可以嘗試 https://github.com/monlor/docker-xiaoya ，我在`WSL2 Ubuntu 22.04` 測試成功
sudo su
然後運行腳本
