### ISSUE TITLE
alist-tvbox的安装

### ISSUE THREAD

**Issue by Angel0726** [DDS-Derek/xiaoya-alist#59]
我看网上说alist-tvbox挺好的，能够搜视频网站。我想问一下
1、如果想要安装alist-tvbox还需要安装小雅、emby吗？
2、阿里云盘目前免费版只有100G，我安装小雅就使用了160G的元数据。我感觉我的元数据有问题，请问正常的元数据应该多大，是80G吗？安装了jellyfin
![image](https://github.com/DDS-Derek/xiaoya-alist/assets/32816780/cb5d4e97-651c-40f9-83fd-b93f49fc728c)

**Comment by RamenRa** [comment]
![9](https://github.com/DDS-Derek/xiaoya-alist/assets/53000259/ac052b5f-647b-462f-ab92-bea265efc9bb)

**Comment by Angel0726** [comment]
> ![9](https://github.com/DDS-Derek/xiaoya-alist/assets/53000259/ac052b5f-647b-462f-ab92-bea265efc9bb)
> 

我这个是在阿里云盘中看到的目录结构，不是在小雅面板里边

**Comment by DDSDerek** [comment]
> 我看网上说alist-tvbox挺好的，能够搜视频网站。我想问一下 1、如果想要安装alist-tvbox还需要安装小雅、emby吗？ 2、阿里云盘目前免费版只有100G，我安装小雅就使用了160G的元数据。我感觉我的元数据有问题，请问正常的元数据应该多大，是80G吗？安装了jellyfin ![image](https://private-user-images.githubusercontent.com/32816780/322512601-cb5d4e97-651c-40f9-83fd-b93f49fc728c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMzU1NjYsIm5iZiI6MTcxMzIzNTI2NiwicGF0aCI6Ii8zMjgxNjc4MC8zMjI1MTI2MDEtY2I1ZDRlOTctNjUxYy00MGY5LTgzZmQtYjkzZjQ5ZmM3MjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAyNDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyOTkxNjc2ZmYyZjQ2MTZlNDA4NGQ0ZmMxNzdlNmQxYmY5ZTM5Yzg4YTJkMDE0NTkwN2ZjOGRkMjVmYmNhNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WEjiLYGBwMKLw6fbaFWhB8nj8G6ioHqcN9cmWVSs3OE)

1. 只安装alist-tvbox无需安装小雅和emby
2. 元数据是没问题的
