### ISSUE TITLE
增加一个自动更新用户策略的功能，解决library.db替换后非管理员打开空白问题。方法有了，差个自动抓取生成脚本的脚本

### ISSUE THREAD

**Issue by duckeaty** [DDS-Derek/xiaoya-alist#6]
7. 更新：解决更新替换library.db后非管理员帐号打开空白的方法

7.1 找到你的非管理员帐户的用户ID，在 /媒体库目录/config/config/users里查看，目录名的那一串字符就是，比如：f7e087aa8fd**********e38ea604031e5f（星号为我打的码，你找到的应该是一串字符串，以下举例就用这个ID），记录下来，有几个用户就记录几个。下面举例中称为“USERID”
注意，有的是空目录，你自己确定，也可以浏览器访问http://IP:2345/Users?api_key=密钥（看7.2）来查看，“ID”：后的是用户ID。这里是每个用户一个{}，多个用户有多个。7.3部分可以直接查看这个地址，不用一个一个看，所有用户都在这里了。

7.2 进入emby，打开控制台，左边打到最下方，点API密钥，在右边点击“+新API密钥”，应用名称随意，确认后下方会出来你命名的API密钥，比如：20a7bc5d**************7ebf4935e544（星号为打码，同上），记录下来。下面举例中称为“密钥”。

7.3 用浏览器打开：
http://IP:2345/Users/USERID?api_key=密钥，用几个用户就打开几个，自己更换USERID
例：
http://IP:2345/Users/f7e087aa8fd**********e38ea604031e5f?api_key=20a7bc5d**************7ebf4935e544
注意：可以按7.1中浏览器直接打开 http://IP:2345/Users?api_key=密钥 ，所有用户都在这。一个用户一大段，不要遗漏。

7.4 在打开的页面中将“Policy”部分复制下来，应该是这样的：
“Policy"：{
xxxxxxxxxxxx
}
中复制Policy后面{}中的内容，含”{}“。有几个帐户就得到几个，以下称为”用户策略1，用户策略2，......“。

7.5 在 /root下新增一个update_userpolicy.sh的文档，命令行如下：
nano /root/update_userpolicy.sh
将以下内容复制进去（横线中间的部分）：
------------------------
#!bash
USER_POLICY='用户策略'
curl -i -H "Content-Type:application/json" -X POST -d "$USER_POLICY" http://IP:2345/Users/USERID/Policy?api_key=密钥
------------------------

注意1：多用户，有几个用户就就新建几个文件：
update_userpolicy_1.sh
---------------------------------------------
#!/bin/bash
USER_POLICY='用户策略1'
curl -i -H "Content-Type:application/json" -X POST -d "$USER_POLICY" http://IP:2345/Users/USERID_1/Policy?api_key=密钥
---------------------------------------------

update_userpolicy_2.sh
---------------------------------------------
#!/bin/bash
USER_POLICY='用户策略2'
curl -i -H "Content-Type:application/json" -X POST -d "$USER_POLICY" http://IP:2345/Users/USERID_2/Policy?api_key=密钥
---------------------------------------------

注意2：自行替换  用户策略，USERID，密钥，实际参考以下(以一个用户举例)：
--------------------------------------------
#!bash
USER_POLICY='{"IsAdministrator":false,"IsHidden":false,"IsHiddenRemotely":false,"IsHiddenFromUnusedDevices":true,"IsDisabled":false,"LockedOutDate":0,"AllowTagOrRating":false,"BlockedTags":[],"IsTagBlockingModeInclusive":false,"IncludeTags":[],"EnableUserPreferenceAccess":true,"AccessSchedules":[],"BlockUnratedItems":[],"EnableRemoteControlOfOtherUsers":false,"EnableSharedDeviceControl":false,"EnableRemoteAccess":true,"EnableLiveTvManagement":false,"EnableLiveTvAccess":false,"EnableMediaPlayback":true,"EnableAudioPlaybackTranscoding":false,"EnableVideoPlaybackTranscoding":false,"EnablePlaybackRemuxing":false,"EnableContentDeletion":false,"RestrictedFeatures":[],"EnableContentDeletionFromFolders":[],"EnableContentDownloading":true,"EnableSubtitleDownloading":true,"EnableSubtitleManagement":false,"EnableSyncTranscoding":false,"EnableMediaConversion":false,"EnabledChannels":[],"EnableAllChannels":true,"EnabledFolders":[],"EnableAllFolders":true,"InvalidLoginAttemptCount":0,"EnablePublicSharing":false,"RemoteClientBitrateLimit":0,"AuthenticationProviderId":"Emby.Server.Implementations.Library.DefaultAuthenticationProvider","ExcludedSubFolders":[],"SimultaneousStreamLimit":0,"EnabledDevices":[],"EnableAllDevices":true,"AllowCameraUpload":false,"AllowSharingPersonalItems":true}'
curl -i -H "Content-Type:application/json" -X POST -d "$USER_POLICY" http://192.168.1.5:2345/Users/f7e087aa8fd**********e38ea604031e5f/Policy?api_key=20a7bc5d**************7ebf4935e544
-------------------------------------------
按ctr+x保存。

7.6 增加执行权限：
chmod +x /root/update_userpolicy.sh

7.7 加入自动处理
如果你在第4部分设置的是早上6：30执行数据库更新，那这个部分就设置为6：40，留10分钟给emby启动，具体如下：
命令行：
crontab -e
在最后（如有exit 0,放exit 0前面）增加以下内容（单用户）：
40 6 * * * sh /root/update_userpolicy.sh
如果是多用户增加以下内容（多用户）：
40 6 * * * sh /root/update_userpolicy_1.sh && sh /root/update_userpolicy_2.sh
注意，这里有几个用户你应该就有几个文件，按sh /root/update_userpolicy_x.sh增加，用&&来连接
（如果多用户都放到一个文件里会大概率执行报错，原因未知，所以改成了多文件方式。）
然后ctr+x保存

**Comment by DDSDerek** [comment]
https://github.com/DDS-Derek/xiaoya-alist/issues/7

**Comment by liang85727** [comment]
http://192.168.1.5:2345/Users/f7e087aa8fd**********e38ea604031e5f/Policy?api_key=20a7bc5d**************7ebf4935e544  使用了emby的ip,用户id和api_key，但是报错‘No such file or directory’，请问怎么破
