### ISSUE TITLE
请问onelist的默认用户名和密码是多少？

### ISSUE THREAD

**Issue by nodis** [DDS-Derek/xiaoya-alist#65]
大佬，我用脚本安装了onelist，安装完访问5245端口直接可以打开登陆界面，但是不知道默认用户名和密码是多少

**Comment by yjj13** [comment]
可以去根目录 /etc/onelist 里面找文件，把你要设置的账号密码添加进去。
# 管理员账户设置，用于初始化管理员账户
UserEmail=***@qq.com
UserPassword=onelist
测试过已经成功！
