### ISSUE TITLE
ERROR] config.mp4 下载不完整，文件大小(in KB):96 小于预期

### ISSUE THREAD

**Issue by manza7014** [DDS-Derek/xiaoya-alist#68]
<img width="642" alt="image" src="https://github.com/DDS-Derek/xiaoya-alist/assets/19200717/79759e64-c03a-4509-82a2-92793190e6ae">
<img width="1439" alt="image" src="https://github.com/DDS-Derek/xiaoya-alist/assets/19200717/768172ae-ebf5-4546-8dee-99c1808f8c36">
<img width="798" alt="image" src="https://github.com/DDS-Derek/xiaoya-alist/assets/19200717/8a6da56e-45c0-45cc-b6be-0be617ae1f0f">

哪位大佬知道为什么吗？

**Comment by DDSDerek** [comment]
看一下小雅后台日志，试试看元数据文件是否能播放，如果不行就换token

**Comment by xibaluo** [comment]
> 看一下小雅后台日志，试试看元数据文件是否能播放，如果不行就换token

同样的问题，确认过元数据文件都能正常播放

**Comment by wule108** [comment]
清理你的 阿里云盘 保证40G以上的空闲空间

**Comment by NextPoXiao** [comment]
检查你的阿里云盘是不是快满了
