### ISSUE TITLE
关于脚本简化

### ISSUE THREAD

**Issue by Akimio521** [DDS-Derek/xiaoya-alist#69]
感觉部署起来太麻烦了，特别是 xiaoyaliu/alist，居然不同标签使用的端口还不同，而且还用在 config目录下使用txt来“传参”
有没有考虑过使用 docker compose 的方式启动多个容器，并且 docker compose 可以很方便的传参，设置环境变量，可惜 xiaoyaliu/alist 没有开源

我的建议是使用docker bridge 来连接容器，把 xiaoyaliu/alist 的容器名改为xiaoya.host，然后使用的镜像标签是 hostmode，这样就可以直接通过compose 的 docker 网络连接容器（手动创建 docker 网络也行）这样emby访问 strm是正常的，也不用担心宿主机的 5678 端口被占用，如果没有直接访问的需求甚至可以不开相关端口，只保留一个 2345 的端口，然后 2345 反代的地址也可以通过docker 网络直接获取 emby 的地址

这样操作不会造成宿主机开放多个无需直接访问端口，也不用担心宿主机的所在的局域网络环境不同

**Comment by DDSDerek** [comment]
这边会考虑一下，需要脚本大改

**Comment by Akimio521** [comment]
请问你这边能知道xiaoyaliu/alist 内部的一些代码的情况吗，我看enterpoint.sh 是经过加密的，至于 alist 部分的 go代码我就没有看了，不知道有没有编译成二进制，把一个非开源非商业化的软件放在一个联网的环境下运行多少还是有点担心的

**Comment by DDSDerek** [comment]
目前只有 `xiaoyaliu/alist` 这个镜像是闭源的，代码我们都是审核过的，闭源也是因为避免不必要的麻烦。

**Comment by Akimio521** [comment]
请问hostmode 和 latest 这两个标签的具体有什么不同吗，目前最直观的感受就是 nginx 的端口不同

**Comment by DDSDerek** [comment]
是的，也就这一个区别

**Comment by Akimio521** [comment]
有没有考虑以后只使用一个标签，把`hostmode`改成`latest`，在一键脚本把`5678:80`改成`5678:5678`
