### ISSUE TITLE
同步library.db后保留用户播放记录的方法

### ISSUE THREAD

**Issue by duckeaty** [DDS-Derek/xiaoya-alist#7]
4.无人值守更新emby的library.db*数据库，做到完全自动化（替换后如果非管理员帐号打开空白，请参照本文7）
以root用户在命令行输入：
crontab -e
在最下方加入以下2行内容：
30 6 * * * /usr/bin/docker stop emby
0 7 * * * /usr/bin/docker start emby
然后ctr+x保存
上面现行的计划任务是在早上6点30关闭emby,这时resilio会同步library.db*这几个数据库文件，然后在7点重新开启emby（3个数据库文件大概3个多G，半小时够了，如果带宽小，可以把间隔时间增加）。

另一种方法（更不容易出错，但更麻烦）：
4.1 在docker里停止emby

4.2 在 /媒体库目录 下新建一个config_data目录，然后把 /媒体库目录/config/data里的内容移动到新建的 /媒体库目录/config_data中（命令行为：mv -rf /媒体库目录/config/data/* /媒体库目录/config_data/）

4.3 在docker中emby的volume增加映射：/媒体库目录/config_data  ---->  /config/data，（注意是新增，原来的config映射不要动），建议用portainer设置简单一点。

4.4 然后在resilio中同步config，目录选择config，同上选择性更新cache,metadata,data/library.db共2个目录1个文件。

4.5 计划任务（debian举例，其它系统自行摸索吧，软路由系统或群晖的话一般直接有地方设置）：
命令行下输入：
crontab -e
然后在最下面增加（这个不保留用户数据，如要保留看下面）：
30 6 * * * docker stop emby && rm -f /媒体库目录/config_data/library.db* && cp -f /媒体库目录/config/data/library.db /媒体库目录/config_data/ && docker start emby
然后ctr+x保存。

如果要保留用户数据：
先安装sqlite(debian 举例，其它系统自行解决):
apt install sqlite3
然后
crontab -e
30 6 * * * docker stop emby && rm -f /root/xiaoya_emby_library_user.sql && sqlite3 /媒体库目录/config_data/library.db ".dump UserDatas" > /root/xiaoya_emby_library_user.sql && rm -f /媒体库目录/config_data/library.db* && cp -f /媒体库目录/config/data/library.db /媒体库目录/config_data/ && sqlite3 /媒体库目录/config_data/library.db "DROP TABLE IF EXISTS UserDatas;" && cat /root/xiaoya_emby_library_user.sql | sqlite3 /媒体库目录/config_data/library.db && docker start emby

**Comment by DDSDerek** [comment]
thanks
