### ISSUE TITLE
关于同步的问题

### ISSUE THREAD

**Issue by ningcol** [DDS-Derek/xiaoya-alist#76]
Resilio-Sync、小雅元数据定时爬虫、同步定时更新任务，这三个东西是不是都是为同步最新的元数据准备的？只要在三种方案选择里选择一个方案就行了吧？还是他们之间有什么区别？

**Comment by pureair** [comment]
https://www.bilibili.com/read/cv32406757/  根据这个的说法, Resilio-Sync和小雅元数据定时爬虫做的是同一件事情, 只需要2选1

**Comment by pureair** [comment]
教程/文档里的"累死鸟"就是Resilio (花了一上午才领悟到), 所以官方现在已经放弃Resilio了, 原话:"已经放弃累死鸟了（自行删除），请用爬虫更新"

**Comment by rxda** [comment]
> 教程/文档里的"累死鸟"就是Resilio (花了一上午才领悟到), 所以官方现在已经放弃Resilio了, 原话:"已经放弃累死鸟了（自行删除），请用爬虫更新"

原来是这么回事啊，终于搞明白了，感谢！赶紧把Resilio删了，占用有点高
