### ISSUE TITLE
Mac m1 安装报错

### ISSUE THREAD

**Issue by Kissxsis0410** [DDS-Derek/xiaoya-alist#77]
![CleanShot 2024-04-29 at 14 35 05@2x](https://github.com/DDS-Derek/xiaoya-alist/assets/57342367/02ff4bde-fa54-44db-91eb-9f8f96c5c1f3)
![CleanShot 2024-04-29 at 14 35 24@2x](https://github.com/DDS-Derek/xiaoya-alist/assets/57342367/2b54a5d7-496f-4c48-9314-10c4a4163ff2)
![CleanShot 2024-04-29 at 14 35 31@2x](https://github.com/DDS-Derek/xiaoya-alist/assets/57342367/1f20db35-2665-4fe9-bbdb-6d252c057760)
docker 给配置了200g的空间，硬盘还有600g，安装一直提示找不到空间是什么问题啊？

**Comment by cheng10** [comment]
别在macOS上跑了，这个脚本写的挺烂的，没有做跨平台测试。

**Comment by Afcar** [comment]
他的脚本只兼容了linux，好在与mac的冲突不大。

1. 手动下载该[shell脚本](https://fastly.jsdelivr.net/gh/DDS-Derek/xiaoya-alist@latest/all_in_one.sh)，用文本编辑器打开，全文替换
`sed -i`
为
`sed -i'' -e`

2. 修改 /etc/hosts 文件，尾部加一条：
`(你的小雅运行机器的ip)    xiaoya.host`

3. 最后再执行该shell
`sudo bash all_in_one.sh`
