### ISSUE TITLE
小雅助手推送的不是自己的账号是怎么回事？

### ISSUE THREAD

**Issue by lucienyida** [DDS-Derek/xiaoya-alist#80]
![微信图片_20240430172522](https://github.com/DDS-Derek/xiaoya-alist/assets/96853173/f8146683-b0de-4620-abf5-7e1ed3b8938f)
如图，中间是我的账号，是我昨天重新部署一下以后运行的信息，
后面包括再次部署之前的[吾名刘看山]这个账号不是我。

关键是容器内 /data 目录中的token以及mytoken都换成我自己账号的数据。

**Comment by DDSDerek** [comment]
![image](https://github.com/DDS-Derek/xiaoya-alist/assets/108336573/fcabb810-b2af-4c06-a341-957020c2e33a)
