### ISSUE TITLE
搭建好播放的时候出现 BadRequest:driveId, fileId cannot be empty

### ISSUE THREAD

**Issue by cometzhang** [DDS-Derek/xiaoya-alist#83]
如题

**Comment by wyqsky** [comment]
刚试过了不行，地址栏地址已变（https://www.aliyundrive.com/drive/file/all/6689d8bc4b），中间多了all，最新的版本。如何解决

**Comment by hotinewang** [comment]
我的阿里云盘里压根没有用资源库啊！！！

**Comment by dreamingboat** [comment]
一样的问题，阿里云盘没有资源盘了。怎么解决？

**Comment by 3356153957** [comment]
> 一样的问题，阿里云盘没有资源盘了。怎么解决？

我是换成host部署解决了

**Comment by Hoking007** [comment]
我也遇到同样的问题，没有资源盘了，文件夹id是对的，无法找到转存文件夹，路径中间少了resource，多了一个all

**Comment by GitHub-LP** [comment]
针对这个问题我的尝试是，把类型改为了a，因为资源盘前缀为r，备份盘前缀为b，所以由此推断可能这是由正则拼接的。
![screenshot-20240730-232751](https://github.com/user-attachments/assets/5dce70d0-4b15-4476-8d0a-0d2ffb6b3fd2)
![screenshot-20240730-232942](https://github.com/user-attachments/assets/7cf0e7e4-794e-4de8-bcba-296964883fc8)

**Comment by birdxs** [comment]
> 针对这个问题我的尝试是，把类型改为了a，因为资源盘前缀为r，备份盘前缀为b，所以由此推断可能这是由正则拼接的。 ![screenshot-20240730-232751](https://private-user-images.githubusercontent.com/84648205/353521396-5dce70d0-4b15-4476-8d0a-0d2ffb6b3fd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDUwNDksIm5iZiI6MTcyMjYwNDc0OSwicGF0aCI6Ii84NDY0ODIwNS8zNTM1MjEzOTYtNWRjZTcwZDAtNGIxNS00NDc2LThkMGEtMGQyZmZiNmIzZmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDEzMTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZmYyYzQ1MjMzODVjMWI1ZTAwNmVhZWVlOWQyZjM5MTBjZDU4ZDk0NzY3NGMyM2E3NTE3ZWFjNzc0MTVjYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.brpnMBHyYUs55zUnztNl2d9RYQjmQGrkc8AtqT0LCtw) ![screenshot-20240730-232942](https://private-user-images.githubusercontent.com/84648205/353521407-7cf0e7e4-794e-4de8-bcba-296964883fc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDUwNDksIm5iZiI6MTcyMjYwNDc0OSwicGF0aCI6Ii84NDY0ODIwNS8zNTM1MjE0MDctN2NmMGU3ZTQtNzk0ZS00ZGU4LWJjYmEtMjk2OTY0ODgzZmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDEzMTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhMzVhYzk0MWRlN2EyZjZiYmU0MTVjOTAxMjlmZWI1NGM1OTA1ZWFiZTI5MTc1YTA4NjU3MDQxNTEyZDE3ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZnR6jkKXTN5susi1x5HlldtfvKW7-gKrWMZitZlQ9dk)

修改为a之后你那边可以用了吗？我将r修改为a还是报错BadRequest:driveId, fileId cannot be empty

**Comment by fang-xu-1995** [comment]
有人可以解决么，我尝试了前缀为a也不行

**Comment by linql85** [comment]
有人解决了吗？
