### ISSUE TITLE
x86_64_Ubuntu Server 22.04 系统下小雅容器内读取不到/etc/xiaoya目录的问题

### ISSUE THREAD

**Issue by wukongdaily** [DDS-Derek/xiaoya-alist#85]
如题，发现了一个非常奇怪的问题。此问题在ARM64平台的Ubuntu Server系统未发现。但是在x86_64的Ubuntu Server出现。

```bash
'tvbox.zip' saved
cat: can't open '/data/mytoken.txt': No such file or directory
Thu May 2 17:17:43 CST 2024 current index file version is updated, no need to upgrade
httpd: bind: Address in use
请检查已正确配置 mytoken.txt myopentoken.txt temp_transfer_folder_id.txt 后再重启容器
```
在宿主机检查/etc/xiaoya目录 已经包含了mytoken.txt myopentoken.txt temp_transfer_folder_id.txt 这三个文件并且不为空。
日志提示` cat: can't open '/data/mytoken.txt': No such file or directory`
由于容器一直在重启中，所以不好定位，但是迅速打印容器内/data目录确实没有映射成功。容器内/data 是空的。
所以我干脆自己新建一个别的目录 `/mnt/xiaoya` 
将mytoken.txt myopentoken.txt temp_transfer_folder_id.txt 这三个文件拷贝到 `/mnt/xiaoya` 目录下
然后执行
```basg
docker run -d -p 5678:80 -p 2345:2345 -p 2346:2346 -v /mnt/xiaoya:/data -v /mnt/xiaoya/data:/www/data --restart=always --name=xiaoya xiaoyaliu/alist:latest
```
这次就成功了，日志显示正常更新数据库，也不报错了。

另外如果增加 `--privileged `参数也能正确读取`/etc/xiaoya`，貌似是敏感目录的权限问题？
```bash
docker run -d --privileged -p 5678:80 -p 2345:2345 -p 2346:2346 -v /etc/xiaoya:/data -v /etc/xiaoya/data:/www/data --restart=always --name=xiaoya xiaoyaliu/alist:latest
```
这就是我遇到的问题，如果xiaoya有空可以帮忙看看吗，谢谢！🙏

**Comment by cheng10** [comment]
非常有用。我也遇到了一样的问题。不过我是通过把docker bind改成了docker volume解决的。
你换了目录解决了的话，真的很有可能是/etc目录权限的问题。

**Comment by Sicheng-zju** [comment]
确实是权限的问题

**Comment by flywalt** [comment]
问题+1，我在扫码的时候就遇到扫码成功，网页反馈成功，但是后端写入失败需要手动写入token的问题

INFO:root:等待用户扫码...
INFO:werkzeug:192.168.2.149 - - [10/Nov/2024 21:17:45] "GET /status HTTP/1.1" 200 -
INFO:werkzeug:192.168.2.149 - - [10/Nov/2024 21:17:46] "GET /status HTTP/1.1" 200 -
INFO:werkzeug:192.168.2.149 - - [10/Nov/2024 21:17:47] "GET /status HTTP/1.1" 200 -
INFO:root:等待用户扫码...
INFO:werkzeug:192.168.2.149 - - [10/Nov/2024 21:17:48] "GET /status HTTP/1.1" 200 -
INFO:werkzeug:192.168.2.149 - - [10/Nov/2024 21:17:49] "GET /status HTTP/1.1" 200 -
INFO:werkzeug:192.168.2.149 - - [10/Nov/2024 21:17:50] "GET /status HTTP/1.1" 200 -
INFO:root:扫码成功, refresh_token 已写入文件！
INFO:werkzeug:192.168.2.149 - - [10/Nov/2024 21:17:51] "GET /status HTTP/1.1" 200 -
[INFO] 操作全部完成！
[INFO] 输入你的阿里云盘 Token（32位长）
TOKEN:

手动输入完成以后，启动容器得到类似主贴的日志报错，检查三个文件都在，但是去docker映射里面就有遗失的文件

**Comment by voncamel** [comment]
哇，帮大忙了，我一模一样，反复读取，我还以为token有问题，搞了几次害得被风控了，正在冷却中。
请问有没有更好的简单一劳永逸的方法解决
