### ISSUE TITLE
arm架构机器，脚本运行报错参数太长，自动清理脚本不清理非官方安装目录

### ISSUE THREAD

**Issue by chaomarks** [DDS-Derek/xiaoya-alist#86]
提示这个报错，是不是机器太次了，arm64的机器，小雅官方命令可以安装，但是目录不可控，我想要把目录改一下一下
-sh: /bin/bash: Argument list too long

**Comment by chaomarks** [comment]
我把脚本下载到本地运行可以安装了，又有个问题自动清理脚本的默认目录是不是还是官方的默认目录/etc/xiaoya,还是根据xiaoyaalist的docker容器的配置文件获取token和文件夹ID来清理，好久都没见到清理

**Comment by DDSDerek** [comment]
请问您这边解决了吗？
