### ISSUE TITLE
安装时总是提示config_jf.mp4 下载不完整，文件大小(in KB):96 小于预期

### ISSUE THREAD

**Issue by jasonyun** [DDS-Derek/xiaoya-alist#90]
安装时总是提示config_jf.mp4 下载不完整，文件大小(in KB):96 小于预期
或者是al_jf.mp4不完整

**Comment by jasonyun** [comment]
![image](https://github.com/DDS-Derek/xiaoya-alist/assets/738056/a6930a3e-6a18-4975-b90a-278c05dd08a1)
![image](https://github.com/DDS-Derek/xiaoya-alist/assets/738056/4c7077b4-c760-4603-9ebd-24f006e7f343)
![image](https://github.com/DDS-Derek/xiaoya-alist/assets/738056/c7f06415-983a-4c1c-915b-926c1b650e69)

**Comment by Admingyu** [comment]
+1

**Comment by Admingyu** [comment]
已解决，检查你的阿里云盘是不是快满了，之前的小雅文件夹可以删了，然后腾出来60g左右就差不多了

**Comment by bigBoLang** [comment]
[INFO] 设置目录权限...
[INFO] 精准校验文件大小模式
[INFO] all.mp4 REMOTE_METADATA_SIZE: 37881357623
[INFO] all.mp4 LOCAL_METADATA_SIZE: 41505072439
[ERROR] all.mp4 下载不完整，文件大小(in KB):40532300 小于预期


这个是怎么回事
