### ISSUE TITLE
群辉使用Resilio-Syn一键安装后，无法更改容器配，一直提示与其它设备使用的其它端口冲突

### ISSUE THREAD

**Issue by suixing8** [DDS-Derek/xiaoya-alist#96]

**Comment by suixing8** [comment]
群辉使用Resilio-Syn一键安装后，无法更改容器配置，一直提示与其它设备使用的其它端口冲突，也排查了确实没有使用改端口

**Comment by JinruiWang** [comment]
> 群辉使用Resilio-Syn一键安装后，无法更改容器配置，一直提示与其它设备使用的其它端口冲突，也排查了确实没有使用改端口

群晖的FTP服务使用了5开头的很长一段端口，虽然FTP没开，但是也提示端口占用。换端口吧
