### ISSUE TITLE
安装小雅一直报：The input parameter refresh_token is missing

### ISSUE THREAD

**Issue by ZhelinCheng** [DDS-Derek/xiaoya-alist#97]
今天重装了系统，所以重新安装小雅，完全按照文档操作，重试了很多次
![屏幕截图 2024-05-17 234714](https://github.com/DDS-Derek/xiaoya-alist/assets/16441850/0844c0dd-6945-4bd3-9bbc-33013e7dd6d3)

**Comment by hsj01** [comment]
同报错，我的小雅也是报这个错误，上面还报json错误

Sat May 18 16:34:12 CST 2024 User's guest password has been updated into database successfully
Sat May 18 16:34:12 CST 2024 Mandatory Login has been enabled
Runtime error near line 2: malformed JSON
Runtime error near line 3: malformed JSON
Runtime error near line 4: malformed JSON
Runtime error near line 5: malformed JSON
Runtime error near line 6: malformed JSON
Runtime error near line 7: malformed JSON
Runtime error near line 8: malformed JSON
启动容器(Bridge模式)......
INFO[2024-05-18 16:34:12] reading config file: data/config.json
INFO[2024-05-18 16:34:12] load config from env with prefix:
INFO[2024-05-18 16:34:12] init logrus...
INFO[2024-05-18 16:34:12] start server @ 127.0.0.1:5244
ERRO[2024-05-18 16:34:14] failed get enabled storages: failed to refresh token: The input parameter refresh_token is missing. Please refer to document.
failed init storage
github.com/alist-org/alist/v3/internal/op.initStorage
        /app/internal/op/storage.go:99
github.com/alist-org/alist/v3/internal/op.LoadStorage
        /app/internal/op/storage.go:80
github.com/alist-org/alist/v3/internal/bootstrap.LoadStorages.func1
        /app/internal/bootstrap/storage.go:23
runtime.goexit

**Comment by henryxrl** [comment]
同报错，解决办法就是卸载 xiaoya 容器，然后重新用脚本安装即可。

**Comment by ZhelinCheng** [comment]
> 同报错，解决办法就是卸载 xiaoya 容器，然后重新用脚本安装即可。

我一直是重装系统的，是不是刚好服务恢复了，我在试试

**Comment by sducxh** [comment]
> > 同报错，解决办法就是卸载 xiaoya 容器，然后重新用脚本安装即可。
> 
> 我一直是重装系统的，是不是刚好服务恢复了，我在试试

删掉opentoken_url.txt，再重启容器

**Comment by ZhelinCheng** [comment]
重新安装服务解决，应该是那个时间段小雅容器的问题
