### ISSUE TITLE
有没有人知道这啥情况

### ISSUE THREAD

**Issue by mingtianquan** [DDS-Derek/xiaoya-alist#98]
index.zip            100% |********************************************************************************************************************| 5096k  0:00:00 ETA
'index.zip' saved
Sun May 19 15:24:52 CST 2024 update index succesfully, your new version.txt is 0.9.20
httpd: bind: Address in use
Sun May 19 15:24:52 CST 2024 User's own token 747653383eb24d7a95eecd2ae789b4cb has been updated into database successfully
tvbox.zip            100% |********************************************************************************************************************| 1396k  0:00:00 ETA
'tvbox.zip' saved
Connecting to docker.xiaoya.pro (172.67.178.229:80)
Connecting to gitlab.com (172.65.251.78:443)
saving to 'index.zip'
index.zip            100% |********************************************************************************************************************| 5096k  0:00:00 ETA
'index.zip' saved
Sun May 19 15:24:52 CST 2024 update index succesfully, your new version.txt is 0.9.20
httpd: bind: Address in use
Sun May 19 15:24:52 CST 2024 User's own token 747653383eb24d7a95eecd2ae789b4cb has been updated into database successfully
tvbox.zip            100% |********************************************************************************************************************| 1396k  0:00:00 ETA
'tvbox.zip' saved
Connecting to docker.xiaoya.pro (172.67.178.229:80)
Connecting to gitlab.com (172.65.251.78:443)
saving to 'index.zip'
index.zip            100% |********************************************************************************************************************| 5096k  0:00:00 ETA
'index.zip' saved
Sun May 19 15:24:52 CST 2024 update index succesfully, your new version.txt is 0.9.20
httpd: bind: Address in use
Sun May 19 15:24:52 CST 2024 User's own token 747653383eb24d7a95eecd2ae789b4cb has been updated into database successfully
tvbox.zip            100% |********************************************************************************************************************| 1396k  0:00:00 ETA
'tvbox.zip' saved
Connecting to docker.xiaoya.pro (172.67.178.229:80)
Connecting to gitlab.com (172.65.251.78:443)
saving to 'index.zip'
index.zip            100% |********************************************************************************************************************| 5096k  0:00:00 ETA
'index.zip' saved
Sun May 19 15:24:52 CST 2024 update index succesfully, your new version.txt is 0.9.20
httpd: bind: Address in use
Sun May 19 15:24:52 CST 2024 User's own token 747653383eb24d7a95eecd2ae789b4cb has been updated into database successfully

**Comment by mingtianquan** [comment]
启动不起来！！！

**Comment by sducxh** [comment]
提示端口被占用，看看其它的服务跟小雅有没有冲突
